### ISSUE TITLE
有提供修改default值的接口么？比如：innerRowActions  & filter

### ISSUE THREAD

**Issue by RLwu** [njleonzhang/vue-data-tables#1]
想要去掉默认的操作列，还有是不是可以加大于1的filters？

**Comment by njleonzhang** [comment]
什么叫列操作？你是说列的排序？排序是element-ui的功能，不想要就把sortable属性去掉就好了。
  
```
<el-table-column prop="flow_no"
      label="服务编号"
      sortable="custom">
```

什么叫大于1的filters？你需要多个过滤input？

**Comment by RLwu** [comment]
![image](https://cloud.githubusercontent.com/assets/21750252/22049268/3bf9ed40-dd6d-11e6-8f7c-0402efd134c6.png)
![image](https://cloud.githubusercontent.com/assets/21750252/22049285/51783a28-dd6d-11e6-9be2-87e121327908.png)
怎么把default值换掉？filters好像只能有一个

**Comment by RLwu** [comment]
我需要在两列加过滤

**Comment by njleonzhang** [comment]
现在的过滤会默认过滤所有的属性。你怎在看dist代码，在sorce里看吧。

**Comment by RLwu** [comment]
好吧，sorce里看到的可能满足不了需求。多谢。。

**Comment by RLwu** [comment]
多谢，已经解决了
