### ISSUE TITLE
Actions column to be fixed

### ISSUE THREAD

**Issue by ecerroni** [njleonzhang/vue-data-tables#10]
Please make it possible to fix the action column with the Elements UI `fixed` prop.

**Comment by njleonzhang** [comment]
Tnx for suggestion, will make it soon

**Comment by njleonzhang** [comment]
@ecerroni `fixed` is attribute of `el-table-column`, you should use it directly on `el-table-column`.

**Comment by Grawl** [comment]
@njleonzhang but how can I do this? Action column is generated by `vue-data-tables`, not Element UI.

**Comment by njleonzhang** [comment]
@Grawl You are right. will support this later. Of course, PR is welcomed.

**Comment by njleonzhang** [comment]
add in 1.1.1
