### ISSUE TITLE
Multi Sort

### ISSUE THREAD

**Issue by leiha** [njleonzhang/vue-data-tables#100]
Can we enable many sorts ( at the top columns ( arrows ) ) on the same time ?
( i think no : https://njleonzhang.github.io/vue-data-tables/#/sort )
=> tableProps.defaultSort indicate default sort column and order

I create an application where the multisort will be a good feature
I connected alasql with your table and i reproduce all statements of sql with an ui widget ( ORDER BY too )

**Comment by njleonzhang** [comment]
@leiha element-ui can not support this, this lib rely on it. So I can make it currently.

**Comment by njleonzhang** [comment]
with [custom actionbar](https://njleonzhang.github.io/vue-data-tables/#/defineActionBar) I think you can implement this feature yourself.

**Comment by leiha** [comment]
i'm not sure to understand your mind.
But for additional info to my side , i implemented the multisort system so it's work by my widget
But i can't show all sorts on the top columns ( arrows ) (one only)

**Comment by njleonzhang** [comment]
maybe you can leverage [custom actionbar](https://njleonzhang.github.io/vue-data-tables/#/defineActionBar) to draw a `ui` to show your multi-sort in action bar.

**Comment by leiha** [comment]
ah ok in more of arrows system i create a view for display the setting in the action bar i understand now yours words.

( FYI : )
![screenshot_20171024_111039](https://user-images.githubusercontent.com/3662704/31934359-2cfb814e-b8ac-11e7-8f2a-36da57d2fcc3.png)

**Comment by njleonzhang** [comment]
you draw this `ui` so fast... orz.
As I have claimed, if I make [custom actionbar](https://njleonzhang.github.io/vue-data-tables/#/defineActionBar) support `sort`, it may be easier for you to implement this feature.

**Comment by leiha** [comment]
Maybe better way is :
to see with the developers of elementui for how to access to head columns easyness
i think it's not to you to modify your component
i will open an issue in their tracker , what about think of this ?

**Comment by njleonzhang** [comment]
This is the best solution, but I am afraid element-ui team will not accept this Feature request.

**Comment by leiha** [comment]
I tried , wait and see now ^^ : https://github.com/ElemeFE/element/issues/7688
