### ISSUE TITLE
关于日期范围

### ISSUE THREAD

**Issue by sky429762423** [njleonzhang/vue-data-tables#101]
单个日期可以实现精确筛选，可是没有时间起始范围筛选，该怎么做呢大神

**Comment by njleonzhang** [comment]
你可以用[customize-filter-logic](https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=customize-filter-logic)应该可以很容易的实现

**Comment by sky429762423** [comment]
怎么样把这个filterFunction放到elmentui的日期控件上

**Comment by sky429762423** [comment]
怎么样把这个filterFunction放到 elmentui的日期控件上

**Comment by njleonzhang** [comment]
哦  那你需要用自定义actionbar https://njleonzhang.github.io/vue-data-tables/#/defineActionBar

**Comment by sky429762423** [comment]
谢谢，实现功能了

**Comment by njleonzhang** [comment]
可以把你写的例子贴在出来给其他人参考。
参考： http://jsfiddle.net/zpczjl/9tp3z4bn/

**Comment by sky429762423** [comment]
好的，时间范围筛选请参考：https://jsfiddle.net/sevenyq/wnvwvhbp/
