### ISSUE TITLE
Search in nested data does not work

### ISSUE THREAD

**Issue by krean93** [njleonzhang/vue-data-tables#103]
Hello!

Unofrtunately JSFiddle crashed every time I tried to reproduce the issue, but the point is:

In your table data you have a nested Array, for example : 
![image](https://user-images.githubusercontent.com/26706301/32058169-a29377cc-ba69-11e7-8554-9be3940ec004.png)

You try to render the data somehow like this:
![image](https://user-images.githubusercontent.com/26706301/32058337-03a5099a-ba6a-11e7-8440-f46b241751eb.png)

And you try to search in the nested data attribute's value.

Unfortunately it does not work. 
Probably I have messed up something, could you please clarify?
Thank you very much in advance!

**Comment by njleonzhang** [comment]
@krean93 can you provide the jsfiddle link, which crash?
It seems that the tag `template` is not right. 
`scope.row` should be 
```
{
  test1: ''test2",
  test2: ''test2".
  test3: [
    ......
  ]
}
```

so `scope.row.data` should be undefined. But you claim the table can be rendered as expected, and issue occur when search. I am confusing now.

please provide me a jsfiddle to show your issue. At least, paste code here, not the screen shoot.

**Comment by krean93** [comment]
You are absolutely right, sorry for the mistake. 
It correctly should be "instance in scope.row.test3".
However the problem is that I can not search in this column unfortunately.
 I will try to send the JSfiddle when I get next to a computer.

**Comment by njleonzhang** [comment]
if you have special filter needed, you can use [customize-filter-logic](https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=customize-filter-logic) to custom filter logic

**Comment by krean93** [comment]
Yes I know, I just wanted to know whether nested arrays are supported somehow by default.

**Comment by njleonzhang** [comment]
OK, you can have a try

**Comment by kevrousso** [comment]
@njleonzhang 
I tried to apply a custom-filter on my dataset which has nested properties, and it appears that when applying filters, it doesn't search deeper than the specified property e.g.: 

```js
let data = {
  name: 'Some name',
  id: 1,
  children: {
    name: 'some other name'
  }
}
```

If I specify props: 'name', somehow it only searches on the first name property found.. Is there a way to make deep search filtering?

**Comment by njleonzhang** [comment]
@kevrousso have you tried use https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=customize-filter-logic

**Comment by kevrousso** [comment]
The thing is that I'm using the element-ui filter-method with the @filter-change event.. not using the search for filtering.

How would I be able to search deeper than the 1st level of my data?

**Comment by njleonzhang** [comment]
@kevrousso can you provide a demo to show what you want to do....
