### ISSUE TITLE
the child component of data-tables can't be updated when buttonProps changed

### ISSUE THREAD

**Issue by liuhaozzu** [njleonzhang/vue-data-tables#106]
the action buttons child component of data-tables can't be updated when buttonProps changed.
e.g. when the disabled property was changed to true, the action button would not be changed.

**Comment by njleonzhang** [comment]
would you please provide a reproduce online demo via referencing http://jsfiddle.net/zpczjl/9tp3z4bn/

**Comment by njleonzhang** [comment]
no response, close
