### ISSUE TITLE
highlight-current-row

### ISSUE THREAD

**Issue by bmuangkhot** [njleonzhang/vue-data-tables#107]
Hello,

Could you tell if Element-ui Table attribute "highlight-current-row" is supported on data-tables?
It  is not working with data-tables, but it is with Element el-table.

Any how Thank you for your great work

Cheers

Brice

**Comment by njleonzhang** [comment]
refer to [el-table-table-property](https://njleonzhang.github.io/vue-data-tables/#/renderTable?id=el-table-table-property)

**Comment by bmuangkhot** [comment]
Oh Yes..
Thank you.

**Comment by Lazac92** [comment]
[Updated link](https://njleonzhang.github.io/vue-data-tables/#/en-us/basic?id=pass-props-to-the-embedded-el-table)
