### ISSUE TITLE
Will it be implemented infinity scroll?

### ISSUE THREAD

**Issue by kolesoffac** [njleonzhang/vue-data-tables#109]
Are there plans for it?

Thanks

**Comment by njleonzhang** [comment]
You can leverage `Table Slot` of [el-table](http://element.eleme.io/#/en-US/component/table) to implement infinity scroll?

**Comment by kolesoffac** [comment]
Explain the use of [table-slot](http://element-cn.eleme.io/1.4/#/en-US/component/table#table-slot), please.

**Comment by njleonzhang** [comment]
Hi @kolesoffac, please submit this question about how to use table-slot to element-ui project.
