### ISSUE TITLE
problem of using display:flex 

### ISSUE THREAD

**Issue by TAKA-KII** [njleonzhang/vue-data-tables#115]
I convert it in a translation site and ask you a question.

A column continues lengthening aside when I display a table by the following constitution and is pushed outside a screen.

-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
vue-data-tables@3.0.0
element-ui @ 2.0.4

-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
<div style="display:flex;">
 <div style="flex:1;">
  <data-tabels ...>
   <el-table-column width="60" ...>
   </el-table-column>
   <el-table-column ...> // without width, go expand
   </el-table-column>
  </data-tabels>
 </div>
 <div style="flex:1;">
 </div>
</div>
-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

It does not occur when I set width in all cols.

It is in element from element-ui@2.0.* Behavior in [parent display:flex][child width: 100%] seemed to be changed; [child flex: 1]It is likely that it is necessary to change  of it.
It can reappear by setting el-carousel beside el-table aside.

-- - - - - - - - - - - - - - - - - - - - - - - - - - -
<div style="display:flex;">
 <el-table style="width:100%; ...>
 </el-table>
 <el-carousel style="width:100%; ...>
 </el-carousel>
</div>
-- - - - - - - - - - - - - - - - - - - - - - - -

Because It is not the environment that I can compile, I cannot try it, but probably the correction of the template is necessary
-- - - - - - - - - - - - - - - - - - - - - - - -
index.pug
    el-table(
	...
	style='width: 100% ') ← Cause?
-- - - - - - - - - - - - - - - - - - - - - - - -

Please examine It.

**Comment by njleonzhang** [comment]
@TAKA-KII I am not a native english speaker either. It's hard for me to understand your description from some robot translator.
It seems a css issue, I am not sure wether this is a element-ui issue or vue-data-tables issue.
would you please make a sample to show this issue?

**Comment by TAKA-KII** [comment]
Please accept our apology.

it's prepared sample
----------------------------------------------------------------------------
<template>
  <div style="display:flex">
    <data-tables :data="data">
      <el-table-column v-for="title in titles" :prop="title.prop" :label="title.label":key="title.prop" sortable="custom" :width="title.width" :min-width="title.minWidth" :align="title.align" >
      </el-table-column>
        <el-table-column prop="addcolumn" label="AddColumn" sortable="custom" align="center">
      </el-table-column> 
    </data-tables>
  </div>
</template>

<script>
export default {
  data() {
    return {
      data :[
        {
          "name":"test1",
          "text":"text1",
          "addcolumn":"",
        },
        {
          "name":"test1",
          "text":"text1",
          "addcolumn":"cause",        
        },
      ],
      titles : [
      {
        prop: "name",
        label: "name",
        width: "140"
      }, {
        prop: "text",
        label: "text",
//        width: "auto"
      },
      ],
    }
  },
}
</script>
<style lang="scss" scoped>
</style>
----------------------------------------------------------------------------
impertinent element-ui?

**Comment by TAKA-KII** [comment]
Sorry,　It took time to check a mark down scale

**Comment by TAKA-KII** [comment]
sample run is no problem in this site
http://jsfiddle.net/9tp3z4bn/161/

but , this site don't streth by window.
this sample is no use parameter : width case, isn't strech window size

I think the behavior around the stretch is doubtful.

**Comment by TAKA-KII** [comment]
I identified the cause

.resize-triggers, .resize-triggers > div, .contract-trigger:before
width:100%

but, I do not know who setting ResizeListener
Chart.js ?

direct use el-table case is no problem, vue-data-tables does it make sense?

**Comment by TAKA-KII** [comment]
I identified the cause

el-table parameter [border] 
data-tables default add border parameter 

table-props={ border: false } set pattern don't move,but can't resize table
direct use el-table add border parameter pattern,  no problem and can resize table

I think data-tables have some problem by display:flex and resize

**Comment by njleonzhang** [comment]
@TAKA-KII  if you can not reproduce the issue in jsfiddle, can you make a simple  project which can show this issue? You can open a project in github and just put your demo project there, so that I can understand you better.

**Comment by TAKA-KII** [comment]
The cause is likely to be  el-table bug
https://github.com/ElemeFE/element/issues/7950

Perhaps I think that conditions similar to this are set by chance
Wait till this bug is fixed

**Comment by njleonzhang** [comment]
@TAKA-KII Tnx for your effort.
