### ISSUE TITLE
Can't render html in vue tables

### ISSUE THREAD

**Issue by benedictasamoah** [njleonzhang/vue-data-tables#117]
# Can't render html in tables
I have tried several times to render html in the tables but it's not working please can you assist me with that

**Comment by njleonzhang** [comment]
please provide a repro link to describe your issue.

**Comment by benedictasamoah** [comment]
I'm currently using vue good tables and there is an option for you to render html in the table by just adding this line of code to the field
html:true
But I can't seem to render html in vue-data-tables, I'm new to vue and I have been struglling with this please I appreciate your help

https://jsfiddle.net/wrilben/t6ynttLL/

**Comment by njleonzhang** [comment]
refer to https://github.com/njleonzhang/vue-data-tables/issues/69
