### ISSUE TITLE
Change 'No Data' text

### ISSUE THREAD

**Issue by sylvaincaillot** [njleonzhang/vue-data-tables#120]
Hello,

Is it possible to customize the 'No Data' text in the case of no records for the data-tables-server or the data-tables?

thank you very much

Sylvain

**Comment by njleonzhang** [comment]
`empty-text` prop of `el-table`

**Comment by fergardi** [comment]
And what about the "empty" slot of the "el-table" for customizing the html of the empty case?

**Comment by njleonzhang** [comment]
@fergardi haven't supported, will add in feature version.

**Comment by njleonzhang** [comment]
supported in version 3.4.0
