### ISSUE TITLE
Enable checkbox default value

### ISSUE THREAD

**Issue by IvanBernatovic** [njleonzhang/vue-data-tables#122]
I'm using vue-data-tables on one important project and I need to enable some check boxes by default. We are using checkboxes for filtering data based on status. Main reason we need default checkbox values is for improved user experience as data in table can have irrelevant status (for instance Archived or Ended status). So by default I only want to display relevant data. Right now it's only possible to define `code` and `name` attributes like this:
```
checkboxFilterDef: {
        def: [{
          'code': 'repair',
          'name': 'Repair'
        }, {
          'code': 'help',
          'name': 'Help'
        }],
```
I would like to add one additional non-required boolean attribute `checked` that defines whether specific checkbox is checked by default. So let's say if I want Repair checkbox checked by default I would need this:
```
checkboxFilterDef: {
        def: [{
          'code': 'repair',
          'name': 'Repair',
          'checked': true
        }, {
          'code': 'help',
          'name': 'Help'
        }],
``` 

Hopefully this makes sense for you and you agree that this feature could be helpful in situations like I described. Having said that, I forked this library and implemented simple solution for this so I'll submit PR soon so please check it out. Also I think that it's worth mentioning that there are more checkbox attributes available in Element UI library so there is still room for improvement in this regard, if needed of course.

**Comment by njleonzhang** [comment]
@IvanBernatovic Tnx very much for contribution.  

As you mentioned:
```
there are more checkbox attributes available in Element UI library so there is still room for improvement in this regard, if needed of course.
```

In fact, there are different requirements for users. It's hard for me to make a template to feet everyone's requirement.

So I have designed the customize Action bar. You can define the Action bar by yourself.

https://njleonzhang.github.io/vue-data-tables/#/defineActionBar

For this PR, I will look into it latter. it doesn't take big change and seems very useful. I will consider to merge. Tnx again.

**Comment by IvanBernatovic** [comment]
@njleonzhang Of course, it's completely understandable that it's very hard to make every requirement achieved. That's why we need good community support and a lot of useful contributions :)

Thanks for having a look, I'm not very familiar how library works exactly so I may have missed some things for certain scenarios.

**Comment by njleonzhang** [comment]
search box is removed, please defined your own customize tool bar in 3.4.0
