### ISSUE TITLE
Width action column

### ISSUE THREAD

**Issue by Timz** [njleonzhang/vue-data-tables#124]
Hi! Add please "width" attribute to action column or set width by content

**Comment by njleonzhang** [comment]
@Timz Will consider to add later.
You can [customize Action col](https://njleonzhang.github.io/vue-data-tables/#/defineActionCol) as a workaround.

**Comment by njleonzhang** [comment]
supported in 3.1 with `tableColProps ` in [tableActionCol](https://njleonzhang.github.io/vue-data-tables/#/tableActionCol)
