### ISSUE TITLE
Feature - Row classes 

### ISSUE THREAD

**Issue by aXaki** [njleonzhang/vue-data-tables#125]
Hey, everything looks great except for the 
https://jsfiddle.net/yf5zwsd0/
`:row-class-name="tableRowClassName"`
It is already enabled in the element-ui.

same thing goes for the 
https://jsfiddle.net/6zkuzheu/
`max-height` 
while pagination is disabled (OPTION)

**Comment by njleonzhang** [comment]
please check the [doc](https://njleonzhang.github.io/vue-data-tables/#/renderTable?id=el-table-table-property)
