### ISSUE TITLE
Hide pagination if unnecessary

### ISSUE THREAD

**Issue by sylvaincaillot** [njleonzhang/vue-data-tables#126]
Hi,
I am using the data-tables and pagination-def.
However, if I define my pagesize to be 10 for example but my total number of records to be equal or less than 10, my pagination is still shown.

Is there a way to hide the pagination if the number of records is less than the pagesize?

Thank you for your help

S.

**Comment by njleonzhang** [comment]
Yeah , you can hide the pagination. I forget to document it. I have just added https://njleonzhang.github.io/vue-data-tables/#/pagination

**Comment by sylvaincaillot** [comment]
Thank you, great addition and super quick as usual

This is how I did:
```
methods: {
      isPaginationNeeded () {
        if (this.tableData.length > 10) {          
          return true
        } else {
          return false
        }
      }
    },
    data () {
      return {
        tableProps: {
          border: false,
          stripe: true,
          size: 'mini',
          rowClassName: 'zeroPadding'
        },
        paginationDef: {
          pageSize: 10,
          pageSizes: [10, 20, 50],
          show: this.isPaginationNeeded()
        },
        searchDef: {
          show: false
        }
      }
    }
```

However, i would like to give more flexibility such as

```
isPaginationNeeded () {
        if (this.tableData.length > this.paginationDef.pageSize) {          
          return true
        } else {
          return false
        }
      }
```
but `this.paginationDef.pageSize` gives me an error...

**Comment by njleonzhang** [comment]
You need to handle pagination event to get updated `pageSize`, `this.paginationDef.pageSize` is just the init value.
please provide a online demo if you report issue.

**Comment by ruben82** [comment]
Hi there, link is not working. I'd need to show all row without pagination. I don't want to see it to my html page too.
How can I achieve it pls? Thanks'

**Comment by njleonzhang** [comment]
refer to the layout section in the document.

https://www.njleonzhang.com/vue-data-tables/#/en-us/basic?id=layout
