### ISSUE TITLE
有导出excel的例子吗？

### ISSUE THREAD

**Issue by cag2050** [njleonzhang/vue-data-tables#128]
有导出excel的例子吗？

**Comment by njleonzhang** [comment]
https://njleonzhang.github.io/vue-data-tables/#/event?id=filtered-data

**Comment by cag2050** [comment]
Finally, I use js-xlsx to export .xlsx file, demo: https://github.com/cag2050/vue_tables_xlsx_demo

**Comment by njleonzhang** [comment]
@cag2050 tnx
