### ISSUE TITLE
How set searchBox filter programatically?

### ISSUE THREAD

**Issue by adamturski** [njleonzhang/vue-data-tables#130]
How one can set searchBox input value programatically?

**Comment by njleonzhang** [comment]
with `inputProps`, you can set the value programmatically, but it doesn't trigger the table filter now. I will consider to support in future.

```
      searchDef: {
        props: 'content',
        inputProps: {
          value: 'Repair'
      	}
      }
```

**Comment by adamturski** [comment]
I've created custom searchbox component based on yours implementation. 

It would be great to handle it in the future.

**Comment by njleonzhang** [comment]
@adamturski you can make the custom action bar as a components so that you can reuse it.

**Comment by joernroeder** [comment]
running into the same issue atm. any news on this?

**Comment by njleonzhang** [comment]
@joernroeder currently, just define a customize tool bar to handle

**Comment by njleonzhang** [comment]
search box is removed, please defined your own customize tool bar in 3.4.0
