### ISSUE TITLE
Ideas for improvements - Filter Questions

### ISSUE THREAD

**Issue by globsecure** [njleonzhang/vue-data-tables#133]
# Filters with a **minimum** of characters

**_Problem:_**
- Today, a request is triggered at every character entry in the field.  **This causes a big delay in the requests.**

_**Solution:**_

- Add new props on custom filter (by example: min)

```
{
vals: '',
props: 'name',
min: 3
}

```
# Filters with **dispatch** by button (Filter)

- Today, a request is triggered after change value of inputs filter.

- It would be interesting to trigger the request per button and not for every interaction in the field.

# Thank you for your great work!

**Comment by njleonzhang** [comment]
Tnx for suggestion. currently, you can leverage [debounceTime](https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=related-properties) to migrate this issue; you can also leverage [filterFunction](https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=related-properties) to implement the `min` logic. I am afraid I will not implement this feature in this lib.

**Comment by globsecure** [comment]
Many thanks @njleonzhang , I think maybe my problem might be in the data-table-server then, since search-def has no effect.

Using:
```html
<data-tables-server
      :data="clients"
      :total="total"
      :loading="loading"
      :pagination-def="pagination"
      :action-col-def="actionClient"
      :load-data="loadClients"
      :show-action-bar="false"
      :search-def="searchDef"
      ref="tableClient"
      :custom-filters="filters">
<b-row slot="custom-tool-bar" style="margin-bottom: 10px" :gutter="10">
        <b-col :lg="3" :sm="12" :xs="12">
          <el-input class="form-control-no-border" placeholder="Name" v-model="filters[0].vals"></el-input>
        </b-col>
      </b-row>
</data-tables-server>
```

Configuration:
```javascript
searchDef: {
        show: true,
        debounceTime: 600,
        filterFunction: (el, filter) => {
          return Object.keys(el).some(prop => {
            console.log('vals: ', filter.vals[0])
            if (filter.vals[0].length < 3) {
              return false
            }
            if (prop === 'date') {
              return this.getDate(el.date).indexOf(filter.vals[0]) > -1
            } else {
              return el[prop].toLowerCase().indexOf(filter.vals[0].toLowerCase()) > -1
            }
          })
        }
      },
      filters: [
        {
          vals: '',
          props: 'a1nome'
        },
        {
          vals: '',
          props: 'a1nreduz'
        },
        {
          vals: '',
          props: 'a1cgc'
        },
        {
          vals: '',
          props: 'seller.a3nome'
        }
      ]
```

**Comment by njleonzhang** [comment]
@globsecure `filterFunction` of `data-table-server ` can not work in current design. It's server side's response to do any search or filter. check the [doc](https://njleonzhang.github.io/vue-data-tables/#/serverData?id=server-side-data-source-load-massive-data) for more detail. `show`, `debounce` and any other config except `filterFunction` should be able to work as expect.
If you still encounter issue, please provide a online reproduction via the following boilerplate:
* [Online Demo for front-end pagination](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Online Demo for server-end pagination](https://jsfiddle.net/zpczjl/xboja87c/)
