### ISSUE TITLE
Missing props

### ISSUE THREAD

**Issue by fergardi** [njleonzhang/vue-data-tables#134]
Hello!

I'm missing the following props from el-table:

`size="mini|medium|small"`
`height="250px"`

The former is used for displaying a much compacted data table.
The latter is for scrolling the table instead of paginating it.

Thank you.

**Comment by njleonzhang** [comment]
please provide a online reproduction via the following boilerplate:
* [Online Demo for front-end pagination](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Online Demo for server-end pagination](https://jsfiddle.net/zpczjl/xboja87c/)

**Comment by fergardi** [comment]
* [Front-end table with custom size not working](http://jsfiddle.net/9tp3z4bn/181/) based on the original [element-ui table specs](http://element.eleme.io/#/en-US/component/table#table-attributes) size
* [Back-end table with custom size not working](https://jsfiddle.net/xboja87c/34/) based on the original [element-ui table specs](http://element.eleme.io/#/en-US/component/table#table-attributes) size

* [Front-end table with custom height and scrolling not working](http://jsfiddle.net/9tp3z4bn/183/) based on the original [element-ui table specs](http://element.eleme.io/#/en-US/component/table#table-attributes) height
* [Back-end table with custom height and scrolling not working](https://jsfiddle.net/xboja87c/35/) based on the original [element-ui table specs](http://element.eleme.io/#/en-US/component/table#table-attributes) height

**Comment by njleonzhang** [comment]
please read the doc [el-table-table-property](https://njleonzhang.github.io/vue-data-tables/#/renderTable?id=el-table-table-property)

**Comment by fergardi** [comment]
What about the "fixed" el-table-column property?

**Comment by njleonzhang** [comment]
You write `el-table-column` in your code, you can pass any prop to it. It's not related to vue-data-tables. If the `el-table-column` you mentioned means the action column of vue-data-table, I suggest you to customize a table column instead of using the default, read more: https://njleonzhang.github.io/vue-data-tables/#/defineActionCol

**Comment by fergardi** [comment]
Thank you.
