### ISSUE TITLE
How to custom Table Column?

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#135]
I would like to custom `Table Column`
```
<el-table-column
                        v-for="title in tableTitles"
                        :prop="title.prop"
                        :label="title.label"
                        :key="title.label"
                        sortable="custom"
                >
                    <template  v-if="title.prop == 'code'" slot-scope="scope">
                            {{do anything.....}}
                    </template>
                </el-table-column>
```
Don't show other column (only `code column`).

**Comment by njleonzhang** [comment]
sorry, I can not understand what's your meaning. You can customize table column, please read element-ui doc for more details

**Comment by icangku** [comment]
how to change style of specific element 
ex : i want to change width of input search only but not affecting another component
i've seen about scoped but i don't have access to add like 'data-v-6c0a33b2' how do i do this? thank you

**Comment by njleonzhang** [comment]
@icangku check this example. https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=show-search-box

**Comment by icangku** [comment]
Thanks, it works, but It doesn't work when sort, but sort working when it is raw data
