### ISSUE TITLE
Should change `created() -> mounted()` on Free Mode of Data Server

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#139]
I think that we should change  `created() -> mounted()` on Free Mode of Data Server.
Bc It doesn't show `loading`

**Comment by njleonzhang** [comment]
Sorry, would you please provide a demo to demonstrate your issue via the following boilerplate:

* [Online Demo for front-end pagination](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Online Demo for server-end pagination](https://jsfiddle.net/zpczjl/xboja87c/)

**Comment by njleonzhang** [comment]
close for no reponse
