### ISSUE TITLE
How to size the height  of the rows of a Table

### ISSUE THREAD

**Issue by nssflaos** [njleonzhang/vue-data-tables#140]
Hello,

I wonder if you let me know  how to set the height of the rows of a table.
I did not find any information to size it. 
The only property i saw is "max-height" in the <data-tables> tag, which is assigned to the Table, not to the row.

Thank you for your help.
Brice

**Comment by njleonzhang** [comment]
you can refer to [el-table](http://element.eleme.io/#/en-US/component/table#table-attributes) doc. I think maybe you can leverage `row-style` property to customize table. If you have more issue, you can ask this question in `el-table` repository

**Comment by bmuangkhot** [comment]
Thank you very much.
