### ISSUE TITLE
能让 action-col-def 里 buttonProps 的值，根据每行中一个列的值，来改变样式吗？

### ISSUE THREAD

**Issue by cag2050** [njleonzhang/vue-data-tables#144]
举例：在action col bar中定义了一个下载按钮；如果此行中状态列的值为‘finish’，就让此‘下载’按钮状态为可点击(disabled为false)，其他情况不可点击(disabled为true)。
请问怎样实现？
```
type: 'default',
buttonProps: {
    disabled: false
},
name: '下载'
```

**Comment by njleonzhang** [comment]
那你自己实现这列就行了。就不要用`action-col-def `了。文档里有的 https://njleonzhang.github.io/vue-data-tables/#/defineActionCol
