### ISSUE TITLE
How to delete row in table?

### ISSUE THREAD

**Issue by Xdynix** [njleonzhang/vue-data-tables#146]
# Online reproduce

I've tried this method, but the table contents are not refreshed. The console shows that it was actually deleted from `data`.

https://jsfiddle.net/Xdynix/smwbzf19/

## Context

I'm trying to add a delete button for each row.

Thank you for all your help.

**Comment by njleonzhang** [comment]
I don't know the implement of `_.remove`. But you need to remove the item from the original Array not some copied one.  

```
          handler: row => {
            // _.remove(data, d => d.flow_no === row.flow_no)
            data.splice(data.indexOf(row), 1)
          },
```
