### ISSUE TITLE
Problem or not no icon-more in paginate?

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#147]
![image](https://user-images.githubusercontent.com/4495160/35838030-d5cadd76-0b1b-11e8-9190-373c834c90a2.png)

**Comment by njleonzhang** [comment]
should be your config issue. The online demo doesn't have this issue.
or please provide a online reproduction via the following boilerplate:
* [Online Demo for front-end pagination](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Online Demo for server-end pagination](https://jsfiddle.net/zpczjl/xboja87c/)
