### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by fergardi** [njleonzhang/vue-data-tables#148]
I'm missing the original el-table setCurrentRow method, for specifying the initial selected row of a table.

http://element.eleme.io/#/en-US/component/table#table-methods

http://jsfiddle.net/3nLgwbvh/1/

**Comment by njleonzhang** [comment]
Yeah, I missed this part. You can get ‘el-table’ reference via ref ‘elTable’

The following code make it.
‘’’
<el-table ref='elTable'
‘’’

**Comment by fergardi** [comment]
Any progress on this issue?

**Comment by njleonzhang** [comment]
As I have claimed, you can get `el-table` instance via  ref `elTable` and then call the table methods

**Comment by fergardi** [comment]
Please, provide a better explanation and a working example, cause I cannot got this to work with VueDataTables.

http://jsfiddle.net/e6e2py5x/8/

![image](https://user-images.githubusercontent.com/3602272/38292387-d9dc00c6-37e3-11e8-958e-788011ce5d1f.png)

**Comment by fergardi** [comment]
I finally found it under this route:

`this.$refs.originalReferenceOfMyTable.$refs.elTable.setCurrentRow()`

Thanks!
