### ISSUE TITLE
PaginationDef.currentPage does not update when changing page 

### ISSUE THREAD

**Issue by otolabqu** [njleonzhang/vue-data-tables#149]
I'm using a data-tables with default settings for paginationDef

```
<data-tables :data="schedules"
		       :action-col-def="actionColDef"
		       :search-def="schedulesTableSearch"
			   :pagination-def="paginationDef"
		       class="dataTable">
```

The paginationDef on the controller looks like so, and the settings for pageSize and pageSizes work

```
paginationDef: {
        pageSize: 100,
        pageSizes: [20, 50, 100],
        currentPage: 1
      },
```

When clicking on the frontend to change page, the data-table frontend updates, displaying data correctly, but the `paginationDef.currentPage` variable is still set to 1 (can be seen with Vue dev tools).

![pagination frontend](https://user-images.githubusercontent.com/2772649/36205056-ac7c4f18-118d-11e8-8c6d-7b50508ce19f.png)

![paginationerror2](https://user-images.githubusercontent.com/2772649/36205061-b0b23ade-118d-11e8-8bcd-df957d6f82be.png)

This seems like an error to me. 

Changing the `paginationDef.currentPage` value through dev tools will change the page on the frontend and work as expected.

I worked around this by adding an event listener on the data-tables, and a method to update the paginationDef.currentPage value 

```
<data-tables :data="schedules"
		       :action-col-def="actionColDef"
		       :search-def="schedulesTableSearch"
			   :pagination-def="paginationDef"
		       class="dataTable"
			   v-on:current-change="paginationCurrentPageChanged"
	  >
```

```
methods: {
    paginationCurrentPageChanged(newPage) {
      this.paginationDef.currentPage = newPage
    },
```

This works for my own purpose, but seems like an ugly hack and it seems that the data-tables component does not work as it should, since the pagination variable does not update internally. 

Edit: The same problem seems to apply to the `pageSize` variable. Changing on the frontend works on the frontend, but does not change the data in the component. Changing the data in the component (from dev tools) will affect the component though, and works.

**Comment by otolabqu** [comment]
```
This is the one of the Vue principles. You always use Vue in this way, why do you think this is a an ugly hack?
```

I haven't used Vue very much, so I didn't see that this is one of the principles. 

I think it is an ugly hack because I had to dig inside, find the event name, then write code to explicitly do something I had expected to happen automatically.

I appreciate the quick reply from your side.

**Comment by njleonzhang** [comment]
supported  in version 3.4.0
