### ISSUE TITLE
How to use summary data

### ISSUE THREAD

**Issue by ignishub** [njleonzhang/vue-data-tables#151]
I tried to use Summary as it used in element but it doesnt work =(

**Comment by njleonzhang** [comment]
please provide a online reproduction via the following boilerplate:
* [Online Demo for front-end pagination](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Online Demo for server-end pagination](https://jsfiddle.net/zpczjl/xboja87c/)

**Comment by ignishub** [comment]
http://jsfiddle.net/7cro8u9b/2/

**Comment by njleonzhang** [comment]
refer to: 
http://jsfiddle.net/7cro8u9b/7/

**Comment by ignishub** [comment]
Thank you!
