### ISSUE TITLE
建议增加一个paginationProps 属性

### ISSUE THREAD

**Issue by ac88** [njleonzhang/vue-data-tables#152]
像tableProps属性一样支持所有el-pagination的配置
比如 background

http://element.eleme.io/#/zh-CN/component/pagination

**Comment by njleonzhang** [comment]
感谢建议 你有兴趣 做个PR么

**Comment by ac88** [comment]
@njleonzhang  sorry,现在拼命在忙项目，git github pull相关还没有用过，以后有机会做PR

**Comment by njleonzhang** [comment]
@ac88 好的，谢谢建议。

**Comment by kevrousso** [comment]
Is there any way to add the background attribute to the pagination using vue-data-tables?

**Comment by njleonzhang** [comment]
will support in next version, check this branch: https://github.com/njleonzhang/vue-data-tables/tree/tool_bar

**Comment by njleonzhang** [comment]
supported  in version 3.4.0
