### ISSUE TITLE
Filter-method & paginated datatable

### ISSUE THREAD

**Issue by sylvaincaillot** [njleonzhang/vue-data-tables#153]
Hello, 
I am trying to implement filtering on my paginated datatable following element-UI recommendations:
http://element.eleme.io/#/en-US/component/table#filter

As such:

```
 <data-tables :data="tableData" :table-props="tableProps" :search-def="searchDef" :pagination-def="paginationDef">
        <el-table-column v-for="title in columns" :prop="title.prop" :min-width="title.width" :label="title.label" :key="title.label"
                          sortable="custom"
                          :filters="[{ text: 'XX', value: 'XX' }, { text: 'WW', value: 'WW' }]"
                          :filter-method="filterTag">
        </el-table-column>
</data-tables>
```
However, it only filters the currently displayed pages... It seems to be a recurrent issue #56.

It doesn't seem that Element-UI is going to make a change. Is there a way to bypass this issue in vue-data-tables?

Thank you

Sylvain

**Comment by njleonzhang** [comment]
I can not make it work before element team don't accept my [PR](https://github.com/ElemeFE/element/pull/6740).  If you really need this feature, you need revise code of `element-ui` and `vue-data-tables` yourself. I am really disappointed to `element-ui` team. As you can find, the `pr` is submitted for a long time. But no response till now.

**Comment by jggj21** [comment]
Please can someone help me to solve it, I have the same problem as just filter on page 1, but I don't understand the solution they give with filter-change
