### ISSUE TITLE
`current-change` event is duplicated on <el-table> and <el-pagination>

### ISSUE THREAD

**Issue by choi4450** [njleonzhang/vue-data-tables#154]
`current-change` event namespace is duplicated on `<el-table>` and `<el-pagination>`.
so, we have to compare whether the type of the first argument of event is an object or a number.

Can you fix the event name or have another solutions?

http://element.eleme.io/#/en-US/component/table#table-events
http://element.eleme.io/#/en-US/component/pagination#events

| Event Name | Element | Description | Parameters |
| -- | -- | -- | -- |
| current-change | `<el-table>` | triggers when current row changes | currentRow, oldCurrentRow |
| current-change | `<el-pagination>` | triggers when `current-page` changes | the `new current-page` |

**Comment by njleonzhang** [comment]
Tnx for submit this bug, will fix ASAP

**Comment by njleonzhang** [comment]
fixed in 3.1.4, please update and have a try. https://github.com/njleonzhang/vue-data-tables/blob/master/CHANGELOG.md

**Comment by choi4450** [comment]
It works for me. thanks!
