### ISSUE TITLE
Virtual List / Lazy Repeat

### ISSUE THREAD

**Issue by fergardi** [njleonzhang/vue-data-tables#155]
# Online reproduce

- https://framework7.io/docs/virtual-list.html
- https://onsen.io/v2/api/angular1/ons-lazy-repeat.html

## Context
When using large datasets, DOM renderization can severely hurt the page performance. As oposed to Infinite Scroll, which simply adds more and more items while scrolling, this new options will remove non visible elements from the list as well as adding the new ones, keeping the visible amount the same in every moment, but releasing the DOM from rendering hundreds or thousands of rows which are unused by the eyes of the user.

**Comment by njleonzhang** [comment]
this Lib is not for mobile, so no infinite scroll support. For desktop website, we use pagination to split large datasets. look into the [Doc](https://njleonzhang.github.io/vue-data-tables/#/serverData), this lib provide a solution for your.
