### ISSUE TITLE
Server Side rendering with Nuxt.js

### ISSUE THREAD

**Issue by ahennie** [njleonzhang/vue-data-tables#156]
Currently it's not possible to render this table on the server, which is really important for SEO.

**Comment by Skoulix** [comment]
Element UI is now SSR capable. Having this feature also for vue-data-tables would be awesome.
Thanks.

**Comment by njleonzhang** [comment]
@Skoulix Tnx for your effort and sharing info here. I will try to make this lib support SSR later.

**Comment by njleonzhang** [comment]
@ahennie @Skoulix I have tried to support ssr. You can have a try in this way: 

```
npm i --save vue-data-tables@ssr
```

```
import Vue from 'vue'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import { DataTables } from 'vue-data-tables/dist/data-tables.server'

Vue.use(ElementUI)
Vue.use(DataTables)
```

I have tried in a sample poeject of `nuxt.js` and [vue-hacknew-2.0](https://github.com/vuejs/vue-hackernews-2.0). `vue-data-tables/dist/data-tables.server` can work in both scenario. But I am not familiar with SSR development, so would you please help to try in you project, and give me some feedback.

**Comment by Skoulix** [comment]
Thanks for enhancing the plugin and adding SSR support. Sorry for not being able to reply earlier. I will check the plugin in a SSR environment and I will give feedback a soon as possible.
