### ISSUE TITLE
Could I possibly create a 2-row header?

### ISSUE THREAD

**Issue by Bombay** [njleonzhang/vue-data-tables#158]
hi. 
Thank you for your quick reply.
I have one more question
Could I possibly create a 2-row header?

**Comment by njleonzhang** [comment]
You can have a try, if `el-table` can create, vue-data-tables should be able to make it. 
refer to： https://njleonzhang.github.io/vue-data-tables/#/renderTable?id=el-table-table-property

**Comment by Bombay** [comment]
thanks!! :)
