### ISSUE TITLE
Multiple selectable columns

### ISSUE THREAD

**Issue by fergardi** [njleonzhang/vue-data-tables#160]
Is it possible to have more than one selection type column at the same time?

**Comment by njleonzhang** [comment]
yeah， just refer to element-ui table document.

**Comment by fergardi** [comment]
This is what I was referring to:

![image](https://user-images.githubusercontent.com/3602272/38234736-055658c0-371f-11e8-9459-c741b529e248.png)

**Comment by njleonzhang** [comment]
so what's your issue, please provide a online reproduction via the following boilerplate:
* [Online Demo for front-end pagination](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Online Demo for server-end pagination](https://jsfiddle.net/zpczjl/xboja87c/)

**Comment by fergardi** [comment]
Here is it: http://jsfiddle.net/e6e2py5x/2/

![image](https://user-images.githubusercontent.com/3602272/38261279-0de67538-376a-11e8-8150-9bded70c508e.png)

When you click on one checkboxed column, ALL the checkboxes check, not only the column you clicked. It should only select the checkboxes of the SAME column you clicked on.

**Comment by njleonzhang** [comment]
sorry, I misunderstand you. we can not support this.

**Comment by tripflex** [comment]
For anybody finding this, the original author was talking about "mutliple" columns, just follow instructions on element UI and add the `@selection-change` to `data-tables` as in the example here:
https://element.eleme.io/#/en-US/component/table#multiple-select

For single column selection
