### ISSUE TITLE
Highlighted rows

### ISSUE THREAD

**Issue by ndum** [njleonzhang/vue-data-tables#162]
Hi, Is it possible to build something like here with highlighted rows? 

https://element.eleme.io/#/en-US/component/table#table-with-status

I have seen that you can pass the properties directly with [:table-props](https://njleonzhang.github.io/vue-data-tables/#/renderTable?id=el-table-table-property) but so it's only possible to adjust for example if the table should have a border or not.

Thanks for your help.

**Comment by njleonzhang** [comment]
it should be able to work by just pass `row-class-name` through `table-props`.

**Comment by ndum** [comment]
Hi - Thanks for your help, it's works now.

Respectively: Here's an example, if someone has the same problem.

```
tableProps: {
                stripe: false,
                "row-class-name": function({row, rowIndex}) {
                    if (rowIndex === 1) {
                    	return 'warning-row';
		    } else if (rowIndex === 3) {
                        return 'success-row';
		    }
                    return '';
                }
            }
```

**Comment by njleonzhang** [comment]
@ndum `row-class-name` can be write in camelCase `rowClassName`.
