### ISSUE TITLE
How to get this data

### ISSUE THREAD

**Issue by icangku** [njleonzhang/vue-data-tables#166]
![tst](https://user-images.githubusercontent.com/14269158/38972454-1a62c6c2-4390-11e8-9a1f-90db0919e4c2.png)

I wanna get the name of the groups, how can i do that?
This hasMany relationship, how do I achieve this? Thank you

**Comment by njleonzhang** [comment]
please provide a online reproduction via the following boilerplate:
* [Online Demo for front-end pagination](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Online Demo for server-end pagination](https://jsfiddle.net/zpczjl/xboja87c/)

**Comment by icangku** [comment]
https://jsfiddle.net/alvin_corwin/68xruhg8/3/
But I don't know why it doesnt show

**Comment by icangku** [comment]
done, thank you to try to help
