### ISSUE TITLE
[Question] How do i get value of search box(el-input) query?

### ISSUE THREAD

**Issue by choi4450** [njleonzhang/vue-data-tables#167]
Hi, I want to fill search query value on route query, but i have not found an event listener when search box value is changed. and  i didn't find a way to two-way binding.
Can i get the value of it?

**Comment by njleonzhang** [comment]
maybe you are look for [this](https://njleonzhang.github.io/vue-data-tables/#/serverData)

**Comment by njleonzhang** [comment]
@choi4450 It's a very special feature request. You can fork this repository and add by yourself.
Or you can customize the tool bar refer to the doc, https://njleonzhang.github.io/vue-data-tables/#/defineActionBar
