### ISSUE TITLE
Automatic columns width adjustment

### ISSUE THREAD

**Issue by tsypa** [njleonzhang/vue-data-tables#168]
I's possible to automatic columns width adjustment according to text length?

**Comment by njleonzhang** [comment]
The generated table is a normal `table`. maybe you can try to find answer in [google](https://www.google.com.ph/search?rlz=1C5CHFA_en__655__655&ei=VmPqWqj4GZisjwO8mr7IBQ&q=table+width+according+to+content&oq=table+width+according+to+c&gs_l=psy-ab.3.0.0i19k1j0i8i30i19k1l2.931.4060.0.5144.15.10.0.0.0.0.404.1788.3-4j1.5.0....0...1c.1.64.psy-ab..10.5.1786...0j0i67k1.0.RIViMAdXmX8).

![2018-05-03 9 27 10](https://user-images.githubusercontent.com/13174059/39556627-2fc3dfd6-4eb4-11e8-8024-516b799469c6.png)
