### ISSUE TITLE
Don't understand wanted version `3.3.1`

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#170]
![image](https://user-images.githubusercontent.com/4495160/40264384-86b2afee-5b4c-11e8-97fb-fc1248f3430b.png)

**Comment by njleonzhang** [comment]
It's a beta version currently with `beta` tag. 
```
npm install vue-data-tables@beta
```
It still in developing with big breaking changes. code is in [tool bar](https://github.com/njleonzhang/vue-data-tables/tree/tool_bar) branch

**Comment by njleonzhang** [comment]
version 3.4 is released.
