### ISSUE TITLE
Is it possible to conditionally show actionbuttons?

### ISSUE THREAD

**Issue by nepembr** [njleonzhang/vue-data-tables#173]
https://njleonzhang.github.io/vue-data-tables/#/tableActionCol

I have a datatable showing two different types of data on the rows.

Some of my actionbuttons are only applicable to certain data. Is it possible to show/hide the buttons depending on the row data? 

I have coded the handler function such that it will just alert a warning "not applicable to this row" when clicked on the wrong type of row. But it would be much nicer if I could simply not have the button on the row where it cannot be used.

**Comment by njleonzhang** [comment]
yeah, https://njleonzhang.github.io/vue-data-tables/#/defineActionCol
