### ISSUE TITLE
Column headers don't align with data columns in chrome

### ISSUE THREAD

**Issue by dopyoman** [njleonzhang/vue-data-tables#174]
# Online reproduce
If you check out the any of the data tables in the chrome browser on the documentation page or for example 

* [Server-Side example from documenation](https://jsfiddle.net/cgx67o3p/)

You can see in this screen shot that the lines dividing the column are a pixel off. 

![image](https://user-images.githubusercontent.com/9316711/40972640-067065d4-68ca-11e8-8bf0-7c53f9a989ad.png)

The issue gets worse when the data table gets larger

![image](https://user-images.githubusercontent.com/9316711/40972718-4af3dfec-68ca-11e8-92b2-ed4f5870bb58.png)

In Firefox it doesn't seem to be a problem when tested

**Comment by njleonzhang** [comment]
`header-align` property of el-table-column.

**Comment by dopyoman** [comment]
That doesn't do anything but align the text in the header columns. Maybe I should post the issue on the elementUI repo

**Comment by njleonzhang** [comment]
@dopyoman sorry, I misunderstand the issue. Yeah, it seems a element-ui issue.

**Comment by njleonzhang** [comment]
![image](https://user-images.githubusercontent.com/13174059/41010431-e6f4c592-6969-11e8-8668-c5079399cc0d.png)

The issue doesn't occur in my chrome.
