### ISSUE TITLE
Uncaught TypeError: Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by shady-xia** [njleonzhang/vue-data-tables#175]
之前一直用的3.1.3的版本，今天升级到3.4.0，构建项目的时候提示

> Uncaught TypeError: Cannot read property 'install' of undefined

在控制台看到是Vue.use(DataTables)的时候报的错误，应该是`import DataTables from 'vue-data-tables'`出的问题。

我发现把import改成require的方式引入，这个问题就解决了，但是看到文档上是用的import。

**Comment by njleonzhang** [comment]
这里调整了，请这样导入。
```
import { DataTables } from 'vue-data-tables'
```

3.4版本的变化比较大，请仔细看下文档，然后再决定是否要升级。
