### ISSUE TITLE
How to provide default sort at init for data-tables-server?

### ISSUE THREAD

**Issue by chenpion** [njleonzhang/vue-data-tables#177]
I was hoping to set `sort` of `query-info` at `init`.

**Comment by njleonzhang** [comment]
refer to: https://njleonzhang.github.io/vue-data-tables/#/en-us/basic?id=pass-props-to-the-embedded-el-table

**Comment by njleonzhang** [comment]
have added a section for default sort

**Comment by chenpion** [comment]
I did see this section, but I mean when using `data-tables-server`, it's seems like I can't provide default sort at `init`. Sorry for not mentioning properly.

**Comment by njleonzhang** [comment]
yeah, it can be used with data-tables-server and make the `init` event change. You can have a try

**Comment by njleonzhang** [comment]
好吧，你好像是台湾人。可以说中文了。
