### ISSUE TITLE
Filter with object field?

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#181]
How to use `filter` with object field
```
tableTitles: [
        { label: 'ID', prop: '_id' },
        { label: 'Name', prop: 'obj.name' },
      ],
tableFilters: [
        {
          prop: ['_id', 'obj.name'],
          value: '',
        },
      ],
```

**Comment by njleonzhang** [comment]
please provide a online demo to describe your question

**Comment by thearabbit** [comment]
I will try

**Comment by argotri** [comment]
this is the link for reproduce @njleonzhang  

http://jsfiddle.net/argo12/cro2njqe/8/

**Comment by njleonzhang** [comment]
@argotri Please read the [filter section](https://github.com/njleonzhang/vue-data-tables/blob/master/docs/en-us/filter.md#principle-of-data-tables-filter) in the document. You need to leverage [filterFn](https://njleonzhang.github.io/vue-data-tables/#/en-us/filter?id=leverage-filterfn)

**Comment by argotri** [comment]
Oke thanks for suggestion, i will try it
