### ISSUE TITLE
Getting weird pageSize warning in console

### ISSUE THREAD

**Issue by CristianDuta** [njleonzhang/vue-data-tables#189]
Steps to reproduce:
- open the developer console from Chrome
- load any page with the vue-data-tables
- observe the following warning:
> pageSize 20 is not included in pageSizes[10,25,50,100], set pageSize to pageSizes[0]: 10

screen shot: https://imgur.com/a/cGQJZiT

**Comment by njleonzhang** [comment]
As the warning claimed, you have set pageSize to 20, at the same time pagesSizes to [10,25,50,100], it is conflictive. The lib chose `pageSizes[0]` as a fallback.

**Comment by CristianDuta** [comment]
Here's how I included the component:
<data-tables :data="alertHistory"
                     :table-props="{stripe: false, border: false}"
                     :show-action-bar="false"
                     :pagination-props="{pageSizes: [10, 25, 50, 100], pageSize: 10}"
                     empty-text="There aren't any alerts in history">....</data-tables>

**Comment by CristianDuta** [comment]
The example in the description is from the documentation, the problem is also present in there

**Comment by njleonzhang** [comment]
you can not pass pageSize through `pagination-props`, instead leverage a independent property `page-size` , which support sync modifier. please read the [document](https://www.njleonzhang.com/vue-data-tables/#/en-us/pagination?id=pagination) carefully. 
In addition, if you submit a issue, please following the template and provide a reproduce.
