### ISSUE TITLE
How to display the picture

### ISSUE THREAD

**Issue by sxhjlzl** [njleonzhang/vue-data-tables#19]
How to display the picture？ Thank you

**Comment by njleonzhang** [comment]
你好请看下el-table怎么显示的，一样的就行了。我不太方便给你提供例子，自己找找看

**Comment by sxhjlzl** [comment]
谢谢，还有个问题我想请教下，就是操作项的样式是否可以自己定义，比如定义成el-button 按钮效果

**Comment by njleonzhang** [comment]
暂时没有支持你说的这个功能，你能具体描述下，我后面考虑添加。
你是需要自定义action column里面按钮的样式么

**Comment by sxhjlzl** [comment]
是这个想法，最好可以自定义样式，显的比较灵活，我源码了，发现样式是写死的text类型的button，

**Comment by njleonzhang** [comment]
好的，我最近没空改，你有空也可以帮忙做下，提个PR :) . 或者等我过段时间来做^_^

**Comment by sxhjlzl** [comment]
好的，有空的话我仔细看下源码，考虑下怎么改

**Comment by sorxrob** [comment]
Oh my God why

**Comment by njleonzhang** [comment]
@sorxrob :)

**Comment by njleonzhang** [comment]
add support for customizing action button style in 1.1.1
