### ISSUE TITLE
Can't import vue-data-tables source code

### ISSUE THREAD

**Issue by isnifer** [njleonzhang/vue-data-tables#193]
# Detailed Description
I can't compile the code with webpack when I follow guide from [here](https://www.njleonzhang.com/vue-data-tables/#/en-us/quickStart?id=import-vue-data-tables-source-code).

My webpack.config.js
```js
const PATH_TO_SRC = path.resolve(__dirname, 'src')

module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        include: [
          PATH_TO_SRC,
          path.resolve(PATH_TO_NODE_MODULES, 'vue-data-tables'),
        ],
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: PATH_TO_SRC,
        exclude: file => (
          /node_modules/.test(file) &&
            (!/\.vue\.js/.test(file) &&
              !/vue-data-tables\/src\/mixins\/ShareMixin\.js/.test(file))
        ),
      },
      // ...
    ],
  },
}
```

My `.babelrc`:
```json
{
  "presets": ["@vue/babel-preset-app"],
  "plugins": [
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-object-rest-spread",
    "babel-plugin-lodash",
    "babel-plugin-vue-jsx-sync",
    "babel-plugin-jsx-v-model"
  ],
  "env": {
    "test": {
      "plugins": [
        ["babel-plugin-root-import", {
          "rootPathPrefix": "@",
          "rootPathSuffix": "src"
        }]
      ]
    }
  }
}

```

The error:
```
ERROR in ./node_modules/vue-data-tables/src/mixins/ShareMixin.js 53:12
Module parse failed: Unexpected token (53:12)
You may need an appropriate loader to handle this file type.
|         this.toolBarShow
|           ? (
>             <div class='tool'>
|               {
|                 this.$slots['tool']
 @ ./node_modules/vue-data-tables/src/components/DataTables.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-data-tables/src/components/DataTables.vue?vue&type=script&lang=js&) 7:0-45 14:11-21
 @ ./node_modules/vue-data-tables/src/components/DataTables.vue?vue&type=script&lang=js&
 @ ./node_modules/vue-data-tables/src/components/DataTables.vue
 @ ./node_modules/vue-data-tables/src/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/ClientProfile/RelationshipsTab/RelationshipsTab.vue?vue&type=script&lang=js&
```

Modules:
```json
{
  "element-ui": "^2.4.9",
  "vue-data-tables": "^3.4.4",
  "vue-loader": "^15.4.2",
  "webpack": "^4.21.0"
}
```

@njleonzhang what did I wrong?

**Comment by njleonzhang** [comment]
it seems `transform-vue-jsx` is not configured in your  babel plugin. so are you sure you have installed and configured all the plugins following their documents?

* babel-plugin-lodash
* babel-plugin-vue-jsx-sync
* babel-plugin-jsx-v-model
* babel-plugin-transform-vue-jsx

**Comment by isnifer** [comment]
@njleonzhang I have installed next components:
```json
{
  "@vue/babel-preset-app": "^3.0.5",
  "babel-plugin-jsx-v-model": "^2.0.3",
  "babel-plugin-lodash": "^3.3.4",
  "babel-plugin-vue-jsx-sync": "0.0.5",
}
```
`@vue/babel-preset-app` contains `babel-plugin-transform-vue-jsx` — https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/package.json

**Comment by isnifer** [comment]
Removed `@vue/babel-preset-app`. Installed all plugins manually. The same result.
I would like to provide my package.json and webpack.config.js — https://gist.github.com/isnifer/f8f95c6490a8f55086a3142e704f00bf

**Comment by isnifer** [comment]
A little bit weird. It has been compiled only when I passed config into webpack.config.js:
```diff
-        loader: 'babel-loader',
+        use: {
+          loader: 'babel-loader',
+          options: {
+            presets: [['@babel/preset-env', { modules: false }]],
+            plugins: [
+              ['@babel/plugin-proposal-class-properties', { loose: false }],
+              ['@babel/plugin-proposal-decorators', { legacy: true }],
+              '@babel/plugin-proposal-export-default-from',
+              '@babel/plugin-proposal-export-namespace-from',
+              '@babel/plugin-proposal-object-rest-spread',
+              '@babel/plugin-syntax-dynamic-import',
+              '@babel/plugin-syntax-jsx',
+              '@babel/plugin-transform-runtime',
+              'babel-plugin-dynamic-import-node',
+              'babel-plugin-transform-vue-jsx',
+              'babel-plugin-lodash',
+              'babel-plugin-vue-jsx-sync',
+              'babel-plugin-jsx-v-model',
+            ],
+          },
+        },
```

**Comment by njleonzhang** [comment]
1. You are using babel 7. some plugin not work with babel 7, refer to https://www.npmjs.com/package/@vue/babel-preset-app. So I suggest you wait until all the plugins are ready. 

2. your log shows that event base vue jsx doesn't work either, You can dig further on the reason if you are interested to it by following vue [jsx document](https://github.com/vuejs/babel-plugin-transform-vue-jsx)

**Comment by isnifer** [comment]
### Finally, I have fixed this error.

#### [My `package.json`, `webpack.config.js`, `babel.config.js`](https://gist.github.com/isnifer/05949fa6170f63f0732c1aecb553e3a5)

[Now, time to fix next.](https://user-images.githubusercontent.com/1788245/47707629-5a3f1700-dc3d-11e8-9964-cd8fb1aaaf5c.png)

**Comment by njleonzhang** [comment]
@isnifer great, tnx for sharing. So your .babelrc doesn't work, so you use `babel.config.js`, then things work now?

**Comment by isnifer** [comment]
@njleonzhang Yes. I don't know actually why. But I thought that real paths to babel plugins will solve the problem. And they solved!

**Comment by njleonzhang** [comment]
it seems you haven't register component. look at the [source code](https://github.com/njleonzhang/vue-data-tables/blob/master/src/index.js)

you can register components globally or use as local component.

**Comment by isnifer** [comment]
@njleonzhang Yeah, I saw a source code. Actually, I do not like this idea.
I do not like vue, but I need to write on it. So, I try to create a React from it, lol

**Comment by njleonzhang** [comment]
@isnifer 😂 now I prefer React to Vue too, but Vue is really powerful and easy to use.
