### ISSUE TITLE
How to reset pagination?

### ISSUE THREAD

**Issue by pixelpaulaus** [njleonzhang/vue-data-tables#195]
# Online reproduce
no example

# Expected Behavior
a way to reset the pagination

# Current Behavior
no way to do it from what i can find in docs.

# Steps to Reproduce
try to reset page to 1, and pagesize to default.

# Detailed Description
i would like i way to reset the pagination for when i manually update the table data.

**Comment by njleonzhang** [comment]
property `current-page` supports `sync` modifier, which you can leverage to set the pagination to any number. check the [doc](https://www.njleonzhang.com/vue-data-tables/#/en-us/pagination?id=pagination)
