### ISSUE TITLE
動作項按鈕的row值會影響到表格data的值

### ISSUE THREAD

**Issue by aTommyWu** [njleonzhang/vue-data-tables#197]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**

# Online reproduce
It is important to provide an online sample to reproduce the issue.
https://jsfiddle.net/TommyWu/eywraw8t/471129/

# Expected Behavior
當點選edit按鈕後，在下方的input可以編輯 flow_no 的資料，這一筆資料是來自於row，
編輯下方的input時，應該只有dialogData.flow_no的資料會更改，但同時表格內的資料也會跟著變動

# Current Behavior
當點選edit按鈕後，在下方的input可以編輯 flow_no 的資料，這一筆資料是來自於row，
編輯下方的input時，應該只有dialogData.flow_no的資料會更改，表格內的資料不會變動

非常感謝您

**Comment by FreezingRiver** [comment]
这并不是vue-data-tables的问题，ElementUI的表格本身就存在这个情况

**Comment by njleonzhang** [comment]
@aTommyWu 本质上说这并不是一个 bug, 你在点击按钮的时候把 row 赋值给了 dialogData.

```
handler: row => {
    this.dialogData = row
},
```

然后又对 dialogData 的 flow_no 做了 v-model 绑定。
```
  <input type="text" v-model="dialogData.flow_no">
```

你第一步的赋值中， dialogData 是对 row 的一个弱引用，他们指向的是同一个对象，所以 dialogData 的 flow_no 属性的修改，就是对 row 的修改，也就出现了你看到的这个现象。本质上这是 javascript 运行的方式，非某一个库的 bug。

你这个例子来说，解决也很简单, 做一个深拷贝就行了:

```
handler: row => {
     this.dialogData = { ...row }
},
```
