### ISSUE TITLE
如何在table里面加入超链接

### ISSUE THREAD

**Issue by zhumian** [njleonzhang/vue-data-tables#199]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**

# Online reproduce
It is important to provide an online sample to reproduce the issue.
* [Template for reproducing front-end pagination issue](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Template for reproducing server-end pagination issue](https://jsfiddle.net/zpczjl/xboja87c/)

# Expected Behavior

# Current Behavior

# Steps to Reproduce

# Detailed Description

**For feature request, provide the following section**
# Motivation / Use Case

# Expected Behavior

# Other Information

**Comment by njleonzhang** [comment]
去看下element ui 的文档就知道了。 el-table-column 支持 slot template 的
