### ISSUE TITLE
define the actions for every row

### ISSUE THREAD

**Issue by ibullet-chzn** [njleonzhang/vue-data-tables#2]
If I don't need to operate, how can I cancel the last column

**Comment by njleonzhang** [comment]
We will update and provide more options.

**Comment by RLwu** [comment]
@ibullet-chzn You can modify the DataTables.vue file to delete opration .
@njleonzhang But how can I add another filters that has different check.code ?

**Comment by njleonzhang** [comment]
@RLwu I am working on the project, and try to make more things configurable, including wether showing action bar, multi-column filter and so on, I will finish this in few days. If you have more requirements, please just open a issue, I will consider it. Of coruse, PR is welcomed.

**Comment by njleonzhang** [comment]
@ibullet-chzn with the newest version, use `has-action-col`, you can hide action col.

**Comment by RLwu** [comment]
OK  thanks~   I'm happy if I can 😁Looking forward to new version.

**Comment by njleonzhang** [comment]
貌似都是中国人。。新版本已经上线了。

**Comment by RLwu** [comment]
辛苦~  还是喜欢讲中文啊！O(∩_∩)O
