### ISSUE TITLE
服务端分页如何设置总条数和获取当前页号，当前每页数呢

### ISSUE THREAD

**Issue by sxhjlzl** [njleonzhang/vue-data-tables#20]
服务端分页如何设置总条数和获取当前页号，当前每页数呢

**Comment by njleonzhang** [comment]
这个要看你的业务需求了。这个库现在不一定能支持，你具体描述下，我们可以讨论下

**Comment by sxhjlzl** [comment]
是这样的。
现在的分页是在客户端实现的，也就是说在前端实现的，这样的方法在数据量不大的情况下完全可以满足需求，但是大部分需求数据量应该都会比较大，在前端一次性拉取所有数据，通过前端分页性能不是太好，就需要把分页参数传递给服务端，让服务端去做分页，这个就需要把一些分页参数传递给服务端，服务端也需要返回给前端一些分页参数，需要传递给服务端的参数有：1.当前页号、2.当前每页数，如果分页要放到服务端去做，当然排序的问题也需要放到服务端，要不然排序就是有问题，前端排序的仅仅是当前页查出来的数据的排序，服务端排序就需要再多加2个前端可以获取到传递给服务端的参数：1.排序列。2.排序类型（desc，asc）.
 服务端需要做的事情就是返回数据列，和返回数据总的条数，也就是分页控件里面的total，显示数据总数。赋值给前端控件。
基本上就这些啦。

**Comment by superqbb** [comment]
这个框架不支持后端ajax分页吗？？

**Comment by njleonzhang** [comment]
恩，最近我实在没时间细想这个问题。但是在我看来，分页的细节是业务逻辑，需要自己处理。库要做的只是现实数据……所以，如果说这个库不能支持后台分页，问题在于根据后来返回的页码去显示正确的页码，这个问题可能可以通过el-pagination 的参数解决。

**Comment by njleonzhang** [comment]
如果完全是，后台决定我觉得那没必要用这个库了啊，你直接用element-ui的组件去做就行了。

**Comment by njleonzhang** [comment]
暂时不会支持后端渲染了。
