### ISSUE TITLE
如何手动触动表格刷新事件query-info

### ISSUE THREAD

**Issue by zhumian** [njleonzhang/vue-data-tables#200]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**

# Online reproduce
It is important to provide an online sample to reproduce the issue.
* [Template for reproducing front-end pagination issue](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Template for reproducing server-end pagination issue](https://jsfiddle.net/zpczjl/xboja87c/)

# Expected Behavior

# Current Behavior

# Steps to Reproduce

# Detailed Description

**For feature request, provide the following section**
# Motivation / Use Case

# Expected Behavior

# Other Information

**Comment by njleonzhang** [comment]
请具体描述你的场景，什么叫手动触发。事件是由一些事件触发的。如果你需要访问上一次 queryinfo 的内容，你可以自己用一个变量记录一下。
