### ISSUE TITLE
checkbox列，状态无记录

### ISSUE THREAD

**Issue by XuXiuJuan** [njleonzhang/vue-data-tables#201]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**

# Online reproduce
It is important to provide an online sample to reproduce the issue.
* [Template for reproducing front-end pagination issue](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Template for reproducing server-end pagination issue](https://jsfiddle.net/zpczjl/xboja87c/)

# Expected Behavior

# Current Behavior
当表格有一列el-table-column的type=“selection”时，在第一页选中某个checkbox，切换到第二页，再切换到第一页，第一页的选中状态就没了

# Steps to Reproduce

# Detailed Description

**For feature request, provide the following section**
# Motivation / Use Case

# Expected Behavior

# Other Information

**Comment by njleonzhang** [comment]
这是预期的行为，翻页之后，表格实际重新渲染了，表格本身不会没有做记录。

你可以通过 `selection-change` 事件自己记录选择过的 row，然后在翻页的时候利用 `toggleRowSelection` 方法去实现勾选。

如果这个需求，想要的人多的话，我也考虑，后期在这个库里实现。
