### ISSUE TITLE
服务端排序，点击多次同一个排序列，发现传参post里的sort的prop和order都是null值 

### ISSUE THREAD

**Issue by songbambi** [njleonzhang/vue-data-tables#206]
# Online reproduce
It is important to provide an online sample to reproduce the issue.
* [Template for reproducing front-end pagination issue](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Template for reproducing server-end pagination issue](https://jsfiddle.net/zpczjl/xboja87c/)

# Expected Behavior
服务端排序，点击多次同一个排序列，发现传参post里的sort的prop和order都是null值 #205

{type: "sort", page: 1, pageSize: 5, sort: {prop: null, order: null}, filters: []}
filters: []
page: 1
pageSize: 5
sort: {prop: null, order: null}
type: "sort"

操作：就是正常点击正序，点击倒序，点击正序，如此几次，就出现了null，求解
# Current Behavior

# Steps to Reproduce

# Detailed Description

**For feature request, provide the following section**
# Motivation / Use Case

# Expected Behavior

# Other Information

**Comment by songbambi** [comment]
演示站jsfiddle 的server演示同样存在问题，多点几次

**Comment by njleonzhang** [comment]
@songbambi elment-ui 的排序逻辑是 3 次，第一次点升序，第二次点降序，再点就是不用这列排序， prop 和 order 就会是  null.
