### ISSUE TITLE
IE11 - Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by iparrabb** [njleonzhang/vue-data-tables#208]
# Expected Behavior
That works on IE11

# Current Behavior
Not works

# Steps to Reproduce
Test with IE11

# Detailed Description
Object doesn't support property or method 'includes', this error appears on IE11 || <, any idea?

**For feature request, provide the following section**
# Motivation / Use Case

# Expected Behavior

# Other Information

**Comment by njleonzhang** [comment]
can you provide a reproduce demo? In the [issue template](https://github.com/njleonzhang/vue-data-tables/blob/master/.github/issue_template.md), you can find boilerplate.

**Comment by srbala** [comment]
IE 11 does not have method 'includes', workaround would be adding a polyfill method https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Polyfill 

```js
if (!Array.prototype.includes) {
  Object.defineProperty(Array.prototype, 'includes', {
    value: function(valueToFind, fromIndex) {

      if (this == null) {
        throw new TypeError('"this" is null or not defined');
      }

      // 1. Let O be ? ToObject(this value).
      var o = Object(this);

      // 2. Let len be ? ToLength(? Get(O, "length")).
      var len = o.length >>> 0;

      // 3. If len is 0, return false.
      if (len === 0) {
        return false;
      }

      // 4. Let n be ? ToInteger(fromIndex).
      //    (If fromIndex is undefined, this step produces the value 0.)
      var n = fromIndex | 0;

      // 5. If n ≥ 0, then
      //  a. Let k be n.
      // 6. Else n < 0,
      //  a. Let k be len + n.
      //  b. If k < 0, let k be 0.
      var k = Math.max(n >= 0 ? n : len - Math.abs(n), 0);

      function sameValueZero(x, y) {
        return x === y || (typeof x === 'number' && typeof y === 'number' && isNaN(x) && isNaN(y));
      }

      // 7. Repeat, while k < len
      while (k < len) {
        // a. Let elementK be the result of ? Get(O, ! ToString(k)).
        // b. If SameValueZero(valueToFind, elementK) is true, return true.
        if (sameValueZero(o[k], valueToFind)) {
          return true;
        }
        // c. Increase k by 1. 
        k++;
      }

      // 8. Return false
      return false;
    }
  });
}
```

**Comment by srbala** [comment]
@iparrabb I usually prefers to have polyfills in high level, once per app

**Comment by njleonzhang** [comment]
Yeah, user should handle the polyfill.

**Comment by srbala** [comment]
@njleonzhang It would be good idea to add a note in documentations for IE support, since your datatable has includes methods.

**Comment by njleonzhang** [comment]
@srbala tnx for suggestion, will add to the document.

**Comment by njleonzhang** [comment]
added https://www.njleonzhang.com/vue-data-tables/#/en-us/quickStart?id=polyfill
