### ISSUE TITLE
tool, table, pagination 两两之间添加间距

### ISSUE THREAD

**Issue by zaxlct** [njleonzhang/vue-data-tables#215]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**
如何为 tool, table, pagination 两两之间添加间距？
或者它们之间默认能不能有间距？

# Online reproduce
It is important to provide an online sample to reproduce the issue.
* [Template for reproducing front-end pagination issue](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Template for reproducing server-end pagination issue](https://jsfiddle.net/zpczjl/xboja87c/)

# Expected Behavior

# Current Behavior

# Steps to Reproduce

# Detailed Description

**For feature request, provide the following section**
# Motivation / Use Case

# Expected Behavior

# Other Information

**Comment by njleonzhang** [comment]
间距，你自己加 css 实现就好了啊。
