### ISSUE TITLE
Support Element UI Tables component attributes

### ISSUE THREAD

**Issue by Grawl** [njleonzhang/vue-data-tables#22]
I just want to use row status class via `:row-class-name` attribute but it's not supported in on `<data-tables>` element but works with `<el-table>`.

So, I think there is no supported `<el-table>` attributes at all.

**Comment by njleonzhang** [comment]
@Grawl I haven't support all attributes of el-table currently. :)

**Comment by njleonzhang** [comment]
add in 1.1.1 by prop `tableProps`
