### ISSUE TITLE
如何动态渲染action-def-col?(例如根据每条row的状态，来控制操作按钮的显示隐藏)

### ISSUE THREAD

**Issue by manba24** [njleonzhang/vue-data-tables#220]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**

# Online reproduce
It is important to provide an online sample to reproduce the issue.
* [Template for reproducing front-end pagination issue](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Template for reproducing server-end pagination issue](https://jsfiddle.net/zpczjl/xboja87c/)

# Expected Behavior

# Current Behavior

# Steps to Reproduce

# Detailed Description

**For feature request, provide the following section**
# Motivation / Use Case

# Expected Behavior

# Other Information

**Comment by manba24** [comment]
给每一行的row配置不同的操作按钮

**Comment by njleonzhang** [comment]
https://www.njleonzhang.com/vue-data-tables/#/zh-cn/actionCol?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%A8%E4%BD%9C%E5%88%97

**Comment by manba24** [comment]
哈哈 找了半天 刚刚发现了，谢谢了
