### ISSUE TITLE
How to excute clearSelection() function by vue-date-tables ref?

### ISSUE THREAD

**Issue by user-GitHub-user** [njleonzhang/vue-data-tables#232]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**

# Online reproduce
It is important to provide an online sample to reproduce the issue.

# Expected Behavior
clear selection by excute clearSelection function
# Current Behavior
I have no idea how to do this

**Comment by njleonzhang** [comment]
refer to https://github.com/njleonzhang/vue-data-tables/issues/148, you can leverage refs.

**Comment by user-GitHub-user** [comment]
> refer to #148, you can leverage refs.
it's works ,thanks!
