### ISSUE TITLE
Problem searching on every column

### ISSUE THREAD

**Issue by Pitu** [njleonzhang/vue-data-tables#24]
Hello!

I installed your module and I'm using it on vue2. I was able to add the table and fill it with data, but I can't seem to make the search work. In the documentation says that the default value of `props` is `All` which I assume means it searches on every column? If that's the case, it's not working for me.

I tried passing an array with my column `props` but it's not working either. Right now I have
```html
<data-tables
	:data='table.rows'
	:search-def='{ placeholder: "Search..." }'
	action-col-width='50'
	action-col-label='Actions'>

	<el-table-column 
		v-for="column in table.columns" 
		:prop="column.id"
		:label="column.label"
		:sortable="column.sortable || true">
	</el-table-column>
</data-tables>
```
And my table object looks like this:
```js
{
	columns: [
		{
			id: 'name',
			label: 'Brand name'
		},
		{
			id: 'modules',
			label: 'Active modules',
			sortable: false
		},
		{
			id: 'employees',
			label: 'Employees'
		}
	],
	rows: [
		{
			id: 1,
			name: 'Starbucks',
			modules: '[2,3,4]',
			employees: 20
		},
		{
			id: 2,
			name: 'Reebook',
			modules: '[1]',
			employees: 5
		},
		{
			id: 3,
			name: 'Havanna',
			modules: '[2,3]',
			employees: 100
		}
	]
}
```

But when I search, nothing happens and nothing gets filtered. No error on console either :(
Thanks for your time and hope you can help me out here!

**Comment by njleonzhang** [comment]
@Pitu would you please make a online sample?

[template](https://codepen.io/leonz/pen/peLVrK)

**Comment by njleonzhang** [comment]
closed for no response
