### ISSUE TITLE
Unable to show tree data

### ISSUE THREAD

**Issue by stefanknegt** [njleonzhang/vue-data-tables#245]
# Online reproduce
http://jsfiddle.net/5ecp2nox/41/

# Expected Behavior
The expected behavior is that the row is expandable and collapsable since it has children.

# Current Behavior
The row does not expand or collapse at all.

# Steps to Reproduce
See the fiddle.

# Detailed Description
I am trying to use tree data in the table, but I can't get the child row to expand collapse.

**Comment by njleonzhang** [comment]
I have just tried, it seems cannot work. I will try to make things work ASAP.

**Comment by stefanknegt** [comment]
Thanks, do you have any idea how long it will take?

**Comment by njleonzhang** [comment]
@stefanknegt it works, just refer to https://codepen.io/leonz/pen/JjoKeNx
