### ISSUE TITLE
筛选能加个下拉吗？自己加了个时间筛选

### ISSUE THREAD

**Issue by 531431988** [njleonzhang/vue-data-tables#25]
如题，自己加了个时间筛选成功了，下拉没加出效果，尴尬，第一次用

**Comment by njleonzhang** [comment]
能具体说说么。。。听起来是个高端需求。

**Comment by 531431988** [comment]
老大，你现在不是有个复选框条件筛选吗？在旁边在加一个下拉条件筛选，我加了没成功，但我自己加了个时间筛选的成功了

**Comment by njleonzhang** [comment]
看来有必要提供一个自定义筛选的方案了，人人都有自己想要的筛选方式这样加下去也不是办法。

**Comment by 531431988** [comment]
对对，一般的筛选就是日期（开始结束时间  elementui有插件） 下拉   复选   单选   搜索，就够了，这个data-tables确定很不错，我是菜逼，成功用上，但是筛选这里不太会改，只改了一个日期的

**Comment by njleonzhang** [comment]
我会考虑下怎么做的通用一点，让需要的人自定义，现在觉得我做复选过滤就是个错误的决定。。。

**Comment by 531431988** [comment]
感谢大神，坐等成果

**Comment by njleonzhang** [comment]
只是现在骑虎难下，比较难改。。。。

**Comment by 531431988** [comment]
这这这……就尴尬了，大神你是最棒（胖）的，加油！

**Comment by njleonzhang** [comment]
。。。然后我并不是大神，我试试，一起学习。

**Comment by 531431988** [comment]
其实你这个在加两个东西就完美了，一个时间筛选（开始结束），一个下拉筛选（自己配置下拉数据），所有的筛选条件都可以自由设置是否显示，这样就完美了

**Comment by njleonzhang** [comment]
那你是觉得的完美，别人不一定这么觉得比如突然有人又说需要个范围选择，这个属于业务需求不应该由我这个库来处理。所以我应该定义好通用的接口，让用户能够自己去实现过滤。

**Comment by 531431988** [comment]
时间就是一个范围呀，还有下拉筛选是可以做地区的，这也是范围，在配上精确搜索，其实已经足够了，用户很懒不要给用户太多的选择，这些都是和之前的功能一样，可以自定show

**Comment by njleonzhang** [comment]
时间的格式和普通的不一样的，我只是举个例子，你没办法知道客户的需求是什么。

**Comment by 531431988** [comment]
好吧，大牛期待神作

**Comment by njleonzhang** [comment]
will be available in 2.0, and add in 9cd9231c1619350b16d57675bd932187bac22f7b. refer to [sample](https://github.com/njleonzhang/vue-data-tables/blob/2.0/play/App.vue#L27)
