### ISSUE TITLE
How to open actionCol in new tab

### ISSUE THREAD

**Issue by robertnicjoo** [njleonzhang/vue-data-tables#250]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**

# Online reproduce
It is important to provide an online sample to reproduce the issue.
* [Template for reproducing front-end pagination issue](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Template for reproducing server-end pagination issue](https://jsfiddle.net/zpczjl/xboja87c/)

# Expected Behavior
Open visit link in new tab

# Current Behavior
Visit link opens in same tab

# Steps to Reproduce

```javascript
actionCol: {
  label: 'Actions',
    props: {
      align: 'center',
      width:"230"
    },
    buttons: [{
    {
      props: {
        type: 'secondary',
        size: 'mini',
        icon: 'el-icon-thumb'
      },
      handler: row => {
        this.$router.push({ name: 'SingleProduct', params: { slug: row.slug } })
      },
      label: ''
   }
  }]
},
```

![Screenshot (35)](https://user-images.githubusercontent.com/8672823/72973015-077feb00-3dff-11ea-94ee-0b8290f2adcc.png)

# Detailed Description
I just need to open my visit link in new tab same as `target="_blank"` if it was a tag.

**For feature request, provide the following section**
# Motivation / Use Case
-
# Expected Behavior
-
# Other Information
-

**Comment by robertnicjoo** [comment]
no one has idea?

**Comment by njleonzhang** [comment]
it seems not a an question about this project.
follow stackoverflow to solve your problem: https://stackoverflow.com/questions/4907843/open-a-url-in-a-new-tab-and-not-a-new-window
