### ISSUE TITLE
请问这套组件可以解决elementi-ui的表格在数据量大的时候页面卡顿的问题吗？

### ISSUE THREAD

**Issue by cshenger** [njleonzhang/vue-data-tables#268]
因为业务需求，element-ui的表格在我们的项目中略有卡顿，所以我才想在github上看一看有没有类似解决办法的组件，请问这套组件可以解决elementi-ui的表格在数据量大的时候页面卡顿的问题吗？谢谢

**Comment by njleonzhang** [comment]
不分页一次性加载大量数据么？现在没有做虚拟列表处理呢。
