### ISSUE TITLE
Table row hover - CSS issue

### ISSUE THREAD

**Issue by Lazac92** [njleonzhang/vue-data-tables#27]
On every 2nd row hover, the background didn't change, because the default color's css selector is stronger.

This will override:
`.el-table--striped .el-table__body tr:nth-child(2n) td {
    background: #FAFAFA;
}`

this:
`.el-table--enable-row-hover tr:hover>td {
    background-color: #eef1f6;
}`

Possible solution:
`.el-table--enable-row-hover  .el-table__body tr:hover>td {
    background-color: #eef1f6;
}`

**Comment by njleonzhang** [comment]
I am not sure if this is a issue, but it seems not related to `vue-data-tables` but `el-table` itself.
Please look at http://element.eleme.io/#/en-US/component/table#striped-table

**Comment by Lazac92** [comment]
Its working on the `el-table`, but not in `vue-data-table`. Thats why I think.

**Comment by njleonzhang** [comment]
OK, I will check later

**Comment by njleonzhang** [comment]
@Lazac92 fixed after update `element-ui`. It should be a element-ui bug and now fixed. I haven't update element-ui version for example.
