### ISSUE TITLE
Custom col template

### ISSUE THREAD

**Issue by Chalkin** [njleonzhang/vue-data-tables#28]
How can I modify the output of data in a column?

Example 1: I'm getting a url from the API and I would like make it a full working link:
`<a href="url from api">something</a>`

Example 2: I receive the first name and last name as seperate values. I would like to join them to first name + last name and display them in one column

**Comment by Chalkin** [comment]
To answer myself. As described in [element-ui docs tables](http://element.eleme.io/#/en-US/component/table#fluid-height-table-with-fixed-header-and-columns) I can add a scoped template to achive it.

Can be closed.

**Comment by njleonzhang** [comment]
Hi TNX for your answer
