### ISSUE TITLE
Not able to add any options

### ISSUE THREAD

**Issue by satyachoudhury** [njleonzhang/vue-data-tables#29]
If I try to add any options to datatable. I get this error:
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': ',' is not a valid attribute name.

This does not work. I get the above error:
```
<template>
    <data-tables :data='tableData',
                 :has-action-col='false'>

```
This works:
```
<template>
    <data-tables :data='tableData'>
```

Like I said I am not able to add any options at all. 

Thanks for this excellent component.

**Comment by njleonzhang** [comment]
Please remove the , from template. And try again. The error has told you ^_^

**Comment by satyachoudhury** [comment]
That worked. Thank you so much.

One more question:
In search function it's not taking an array of columns. Here is an example:

```
getSearchDef() {
            return {
                offset: 12,
                placeholder: 'please input searchkey',
                //props: "name", // this works
                props: ['name', 'email', 'birthdate', 'age'] // this doesn't work
            }
        }
```
When I try to use array, I get the following error:

> TypeError: el[prop].indexOf is not a function

What is the purpose of offset?

**Comment by njleonzhang** [comment]
OK, I will check later

**Comment by njleonzhang** [comment]
It seems some of your `props` does not exist . would you please check wether `'name', 'email', 'birthdate', 'age'` all exist in your data source
