### ISSUE TITLE
官方文档打不开了

### ISSUE THREAD

**Issue by yaowenqiang** [njleonzhang/vue-data-tables#291]
Please follow the issue template, or your issue may be closed automatically.

**For bug report, provide the following section**

# Online reproduce
It is important to provide an online sample to reproduce the issue.
* [Template for reproducing front-end pagination issue](http://jsfiddle.net/zpczjl/9tp3z4bn/)
* [Template for reproducing server-end pagination issue](https://jsfiddle.net/zpczjl/xboja87c/)

# Expected Behavior

# Current Behavior

# Steps to Reproduce

# Detailed Description

**For feature request, provide the following section**
# Motivation / Use Case

# Expected Behavior

# Other Information
![图片](https://user-images.githubusercontent.com/994371/198521345-bfa6f08d-63f3-4433-9a2f-5297607c871c.png)

**Comment by njleonzhang** [comment]
已回复，域名忘记续费，被其他人抢注了 :-{
