### ISSUE TITLE
请求添加报表导出为pdf和excel的功能

### ISSUE THREAD

**Issue by gucy1972** [njleonzhang/vue-data-tables#3]

**Comment by njleonzhang** [comment]
我可以将符合过滤出条件的数据通过事件暴露出来，然后你自己调用第三方库去导出pdf和excel。
jsonToExcel的库：https://github.com/agershun/alasql

你觉得这样怎么样？

**Comment by gucy1972** [comment]
思路相同，我也在github上看第三方的export库。vue-data-tables这个库不错，赞!

**Comment by njleonzhang** [comment]
@gucy1972 谢谢使用，我有空把数据暴露出来，你有空也可以提个pr啊。。。:)

**Comment by njleonzhang** [comment]
Done in https://github.com/njleonzhang/vue-data-tables/commit/daef9b8d57502bd4c50668a1d0544b6d830e8e7e

**Comment by cag2050** [comment]
@gucy1972 报表导出为excel的功能，您添加了吗？怎么做的？分享下给我吧

**Comment by njleonzhang** [comment]
不是回答你了么  #128

**Comment by cag2050** [comment]
@njleonzhang 没能成功导出excel格式。有做好的导出excel的例子吗？
我用alasql，报这个错误：https://github.com/agershun/alasql/issues/950
现在我正在用这个插件：https://github.com/SheetJS/js-xlsx/tree/master/demos/vue 
做的例子地址：https://github.com/cag2050/alasql_demo

**Comment by cag2050** [comment]
@njleonzhang 我可以导出.xlsx格式了。
例子地址：https://github.com/cag2050/alasql_demo

**Comment by njleonzhang** [comment]
@cag2050 好的，没理解你的意思

**Comment by Lxiaoacheng** [comment]
@cag2050 老哥出坑了，file-saver + js-xlsx
