### ISSUE TITLE
checkbox-filter-def: 来定义选择过滤的控件

### ISSUE THREAD

**Issue by MrSuperLi** [njleonzhang/vue-data-tables#30]
这个控件，是否存在一个bug？
例子中是写死的，如果我要异步拉取选项会怎样？
通过试验，写死的可以出现这个控件，但是异步之后没有任何显示
问题原因：checkbox-filter-def属性的变化没有让组件更新，这个属性的逻辑处理是否写在mounted钩子里？
如果是，这可能是问题出现的原因，可以使用深度的watch的再次执行该属性的逻辑

**Comment by MrSuperLi** [comment]
看了源码：
```
created: function created() {
....
	    this.innerCheckboxFilterDef = (0, _assign2.default)({}, {
	      props: undefined,
	      def: [],
	      width: 14,
	      offset: 0,
	      filterFunction: undefined
	    }, this.checkboxFilterDef);
....
}
```
这是写在created钩子的，并且在watch上只是监听分页的属性，没有监听checkbox属性：

```
watch: {
	    innerPaginationDef: {
	      immediate: true,
	      handler: function handler(val) {
	        this.internalPageSize = val.pageSize;
	        this.currentPage = val.currentPage;
	      }
	    }
	  }

```
希望完善一下

**Comment by MrSuperLi** [comment]
不过可以曲线解决：
使用v-if来让组件重新挂载
比如：
```
<data-tables
      v-if="showTable"
```
只要watch我们的checkbox选项，首先showTable默认为true。如果checkbox选项变化，就将showTable先设置为false,然后再设置为true:
```
watch:{
      tags: function tags(val,oldVal){
        this.showTable = false;
        this.$nextTick(function(){
          this.showTable = true;
        });
      }
    }
```
这样就会让组件重新挂载，created就会重新执行，checkbox filter也就可以使用

**Comment by njleonzhang** [comment]
恩  没考虑到你说的这样的需求，会尽快改成你说的这个逻辑，当前情况下，可以用`v-if`绕过这个问题，不过毕竟效率会比较差。另外欢迎PR。

**Comment by njleonzhang** [comment]
以前的逻辑是可以实现动态改变checkbox filter的。后来由于一个#18，我改掉了原来的逻辑https://github.com/njleonzhang/vue-data-tables/commit/e6ace026ceb2ec82f5bfa02c462cded4328912b1，
看来需要好好研究下了。

**Comment by njleonzhang** [comment]
fixed and will release in 2.0
