### ISSUE TITLE
Events for pagination

### ISSUE THREAD

**Issue by pilsoftTeam** [njleonzhang/vue-data-tables#32]
Is there a way to trigger the pagination event current-change?
Thanks

**Comment by njleonzhang** [comment]
will proxy this event in next version.

**Comment by gouchangxing** [comment]
请问下一个版本什么时候发布？

**Comment by njleonzhang** [comment]
I am really very busy on company project, I will try to release ASAP

**Comment by njleonzhang** [comment]
proxied in 2.0.3
