### ISSUE TITLE
Is there a way to make the search NOT case sensitive?

### ISSUE THREAD

**Issue by jzucadi** [njleonzhang/vue-data-tables#33]
Is there a way to make the search NOT case sensitive?

**Comment by njleonzhang** [comment]
You can define your own filterFunction for seach box

**Comment by njleonzhang** [comment]
、、、  
searchDef () {
      return {
        placeholder: 'Search',
        width: 0,
        filterFunction (el, filter) {
          return Object.keys(el).some(key => {
            return String(el[key]).toLowerCase().indexOf(filter.val.toLowerCase()) > -1
          })
        },
      }
    },
、、、

**Comment by jzucadi** [comment]
Thanks, very helpful.
