### ISSUE TITLE
Could example to use `dropdown list` in `row-action-def`?

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#34]
I would like to use `dropdown list` in `row-action-def`

![image](https://cloud.githubusercontent.com/assets/4495160/25688215/97da3362-30a7-11e7-8d03-8d5db3010964.png)

Please example

**Comment by chenjiaj** [comment]
I have the same question

**Comment by njleonzhang** [comment]
will support customize action in 2.0

**Comment by njleonzhang** [comment]
refer to https://njleonzhang.github.io/vue-data-tables/#/defineActionBar

**Comment by thearabbit** [comment]
Thanks I will try soon
