### ISSUE TITLE
Set total count of tableData

### ISSUE THREAD

**Issue by oleg-nogin** [njleonzhang/vue-data-tables#37]
Hello, how can I set ":total" value for pagination. In the src pagination total is computed value, but is there any way to change it?

thx =)

**Comment by njleonzhang** [comment]
You can change the data to change the total. As you know total is equal to data's length

**Comment by oleg-nogin** [comment]
@njleonzhang 

Yes, I can do it. API response often contain items(items.length = 30) and totalcount(for example, 1000).Is there any way to set :total = totalcount from API response? If your answer is the only rigth way, close issue please =)

**Comment by njleonzhang** [comment]
What you want is a server side pagination, this library is not for that.
