### ISSUE TITLE
Could I use `transition` when insert/update/remove row?

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#38]
Could I use `transition` when insert/update/remove row?

**Comment by njleonzhang** [comment]
what you mean by `transition`, the css property?

**Comment by thearabbit** [comment]
yes, animate css.

**Comment by njleonzhang** [comment]
you may need leverage element-ui table property: `row-class-name`. It can not use in `vue-data-tables` in this version, and will be able to work in next version. You can take a look:  
https://github.com/njleonzhang/vue-data-tables/tree/2.0

**Comment by thearabbit** [comment]
thanks, waiting...

**Comment by njleonzhang** [comment]
Hi thearabbit， this feature already released in 1,1, you can use `tableProps`
https://github.com/njleonzhang/vue-data-tables/releases/tag/1.1.1

**Comment by thearabbit** [comment]
Good job, I will check it soon 👍
