### ISSUE TITLE
如何获得所选单元格?限定操作按钮的显示,点击"添加"后在最后一列

### ISSUE THREAD

**Issue by cloudty** [njleonzhang/vue-data-tables#39]
感谢你的贡献，data-tables很美观，目前看起来也很好用。
我在使用中遇到点问题，希望能帮我解答下
如题
1、我想在点击某单元格时能通过触发方法,获取该单元格内容,或者说将该单元格修改为input 状态,该如何办到?
2、在某些情况下，我并不想action-col内的按钮显示，我该如何操作？
3、点击某个按钮之后，能否在table最下方或者最上方添加一行均为input 单元格的内容列？

**Comment by njleonzhang** [comment]
1. 获取单元格内容是比较容易做到了，目前我好想没有发送单元格点击的事件，所以你好像拿不到，这个可以下个版本加一下。想把单元格变成input状态，这个可能要看下element-ui是否支持。

2. 有时候想，有时候不想要么？这个暂时做不到，等我有空我可以想想能不能实现。
3. 看起来你是想在表里添加一项，那么你可以弹出一个Dialog 对话框，在里面做一个表单来添加。（我自己是这样实现的）

**Comment by cloudty** [comment]
谢谢你的回答
1、OK，我去看看element-ui
2、就是能不能根据data 中某个字段做为条件，去判定？
3、可恶的产品经理，嫌弃频繁的弹窗

**Comment by njleonzhang** [comment]
@cloudty 关于第二点，简单一想是这样的，等我有空好好想一下:) 最近公司项目太忙了。如果你能帮忙pr就最好了:)

**Comment by cloudty** [comment]
已经换用element 的UI了.越到后面发现需要的功能越来越多了.
麻烦将这个问题关闭吧

**Comment by njleonzhang** [comment]
好的  这个组件并没有特别的可定制，可以参考源码实现自己的。:)
