### ISSUE TITLE
没有监听selection-change事件

### ISSUE THREAD

**Issue by loliconer** [njleonzhang/vue-data-tables#4]
表格可以添加多选列，但是没有监听selection-change事件，这样如果要获取多选的结果就没办法了

**Comment by njleonzhang** [comment]
恩，是的。我回头加下，你提pr贡献下也行哎,^_^

**Comment by njleonzhang** [comment]
Done in https://github.com/njleonzhang/vue-data-tables/commit/daef9b8d57502bd4c50668a1d0544b6d830e8e7e
