### ISSUE TITLE
support server side?

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#40]
I base on `Meteor`.
I have problem with a big data that I get from Mongo.
Support server side or a big data?

**Comment by njleonzhang** [comment]
This lib can not support server side data. I planned to make another lib to support

**Comment by thearabbit** [comment]
Thanks for your reply. before I use `meteor tabular` it is very easy [(Tabular)](https://atmospherejs.com/aldeed/tabular)
Waiting you
