### ISSUE TITLE
could you detail how to use attr of `<el-table-column>`?

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#41]
Please detail how to use attr of `<el-table-column>` such as `prop, label, sortable....`.
Or check on `Element UI`???

**Comment by FisNew** [comment]
And I have the same problem! How to use the attr 'width' of <el-table-column>?

**Comment by njleonzhang** [comment]
hi， would you please make a online sample?
refer to https://codepen.io/leonz/pen/peLVrK?editors=1010

**Comment by alejandrot3** [comment]
I'm having an issue with creating a simple table. and My issue is with the el-table-column. somehow is telling me is an unknown custom element.
The weird thing is, I added all the code required. is creating the rows, is even is creating the action column. but when I try to define my columns, its just saying is an unknown custom element. its driving me insane. have anyone seen this issue?

**Comment by thearabbit** [comment]
I would like to detail how to use prop of `<el-table-column>` in readme.

**Comment by njleonzhang** [comment]
@thearabbit  it is `element-ui` component. please refer to its document. 
http://element.eleme.io/#/en-US/component/table#table-column-attributes

**Comment by thearabbit** [comment]
Thank again, waiting for `get data from server`!!!
