### ISSUE TITLE
`<el-table-column>`width属性

### ISSUE THREAD

**Issue by FisNew** [njleonzhang/vue-data-tables#43]
不知道大佬发现没有，`<el-table-column>`width属性有BUG，无论设置什么值，都会变的很大，不知道是不是我使用的方式不对？

**Comment by njleonzhang** [comment]
我晚上看一下 可以提一个sample么？

**Comment by njleonzhang** [comment]
https://codepen.io/leonz/pen/peLVrK?editors=1010 我用了 有什么问题么？有问题也是element-ui的啊

**Comment by FisNew** [comment]
谢谢，已经解决了，element-ui的原因。
