### ISSUE TITLE
支持远程筛选吗

### ISSUE THREAD

**Issue by chenyihao2621023** [njleonzhang/vue-data-tables#44]
比如，从别的地方，传过来一个 {value:'未解决'}，我想将value这个字段，作为表格的筛选条件，有接口可以调用吗？ 麻烦啦

**Comment by njleonzhang** [comment]
自定义的筛选条件么。暂时好像没有支持，后面会考虑加入。你也可以看下源码，自己改一下还是挺容易改的。:)

**Comment by chenyihao2621023** [comment]
谢谢您的及时回答，还有 这个组件真的很棒！

**Comment by njleonzhang** [comment]
@chenyihao2621023 谢谢
