### ISSUE TITLE
建议支持自定义actions按钮type属性

### ISSUE THREAD

**Issue by wutingye** [njleonzhang/vue-data-tables#48]
建议actions(which belongs to table)按钮支持el-button的type属性，而不是默认不可修改的type='primary'
just like row-actions(which belongs to row)

**Comment by njleonzhang** [comment]
恩  2.0在开发中会支持的。你可以在2.0 branch上看到的

**Comment by zyJGH** [comment]
操作列 里面的button 这么添加?

**Comment by njleonzhang** [comment]
@zyJGH 你这句话什么意思。。。

**Comment by zyJGH** [comment]
![image](https://user-images.githubusercontent.com/19925628/27526815-d475ff3e-5a7a-11e7-84e4-53248b345dde.png)

**Comment by njleonzhang** [comment]
supported in 2.0
