### ISSUE TITLE
How to set to English?

### ISSUE THREAD

**Issue by marlonbuendia** [njleonzhang/vue-data-tables#49]

**Comment by njleonzhang** [comment]
example:
https://github.com/njleonzhang/vue-data-tables/blob/master/example/docs/en.vue#L158

**Comment by marlonbuendia** [comment]
import lang from 'element-ui/lib/locale/lang/en'
import locale from 'element-ui/lib/locale'

locale.use(lang)

Got it! thanks!

**Comment by njleonzhang** [comment]
welcome
