### ISSUE TITLE
请问怎么自定义下拉菜单过滤器

### ISSUE THREAD

**Issue by chenjiaj** [njleonzhang/vue-data-tables#50]
![image](https://user-images.githubusercontent.com/8109018/27730508-035f56f8-5dbc-11e7-9815-d731ef771ea4.png)
请问有没有例子或者详细一点的文档介绍自定义过滤器，我想定义两个下拉菜单过滤器 请问该怎么写，急需，麻烦解答一下，谢谢

**Comment by njleonzhang** [comment]
这个功能2.0才会有，1.0里的这个自定义过滤方法，指的是过滤函数可以自定义。

**Comment by njleonzhang** [comment]
你急需的话，可以参考2.0branch上的代码

**Comment by chenjiaj** [comment]
好的 谢谢

**Comment by njleonzhang** [comment]
refer to https://njleonzhang.github.io/vue-data-tables/#/defineActionBar
