### ISSUE TITLE
你好，请问怎么设置固定表头height？

### ISSUE THREAD

**Issue by RLwu** [njleonzhang/vue-data-tables#51]
![image](https://user-images.githubusercontent.com/21750252/27820793-8c02bd60-60d2-11e7-84a3-43f0ea4f022a.png)

**Comment by njleonzhang** [comment]
2.0里支持，急着用，可以参考2.0代码

**Comment by njleonzhang** [comment]
refer to  https://njleonzhang.github.io/vue-data-tables/#/renderTable?id=el-table-table-property
