### ISSUE TITLE
Optionally disable pagination

### ISSUE THREAD

**Issue by sobolevn** [njleonzhang/vue-data-tables#52]
Hi, thanks for the awesome component!

I would like to disable pagination in some cases. I would really like to have something like `has-pagination` property.

Would you mind a PR from me with this feature?

**Comment by njleonzhang** [comment]
@sobolevn It's OK :). Please work on 2.0 branch. It's better if you can add UT for this feature. no need to write document because I am considering re-write all docs.

**Comment by sobolevn** [comment]
Sorry, did get the `UT` thing. What is it?

**Comment by njleonzhang** [comment]
@sobolevn unit test, sry
