### ISSUE TITLE
`row-action-def` should be a function

### ISSUE THREAD

**Issue by sobolevn** [njleonzhang/vue-data-tables#54]
I want to set different actions to different rows based on the data in the row.
But right now it seems impossible to me.

Any ideas on how to achieve that?

**Comment by njleonzhang** [comment]
currently, you can not customize the action col, I am considering improving in next version.

**Comment by sobolevn** [comment]
Ok, here's a workaround for now:

Steps:
1. disable actions via `:has-action-col="false"`
2. then use this `el-column`:

```vue
  <el-table-column
      label="Actions">
      <template scope="scope">
        <el-button v-for="button in customButtonsForRow(scope.row)" @click="button.handler">
          {{ button.name }}
       </el-button>
      </template>
    </el-table-column>
```

**Comment by njleonzhang** [comment]
@sobolevn Tnx, it seems users can define any col action in this way. This can be a solution, not just workaround. :)

**Comment by njleonzhang** [comment]
added to [doc](https://njleonzhang.github.io/vue-data-tables/#/defineActionCol)
