### ISSUE TITLE
filter-method el-table-column

### ISSUE THREAD

**Issue by Sancho66** [njleonzhang/vue-data-tables#56]
Hi , 

I use "filter-method" and "filters" attributes  on "el-table-column" component with pagination on my table.
Can I filter on ALL rows ( all the pages) instead of rows on the current page ?

Indeed filter-method is called only for rows on the current page...

Thanks

**Comment by njleonzhang** [comment]
if you use `filter-method`, its el-table who manage the filter, not `vue-data-tables`,   `el-table` do not know pagination, so you can only filter current page. I will try to make this work in `vue-data-tables` in feature.

**Comment by Sancho66** [comment]
Okay , thanks !

**Comment by sobolevn** [comment]
Any progress on this one? I am facing it too.

**Comment by njleonzhang** [comment]
`el-table` can not support this feature, I have submit a [PR](https://github.com/ElemeFE/element/pull/6740) to `element-ui`. If the PR can be merged, we can go ahead to support this in `vue-data-tables`

**Comment by sallyruthstruik** [comment]
@Sancho66 Solved in https://github.com/njleonzhang/vue-data-tables/pull/116

**Comment by kevrousso** [comment]
@sallyruthstruik You have an example of how you fixed it? I tried to pass custom filters to vue-data-table but doesn't work...

**Comment by jggj21** [comment]
Please can someone help me to solve it, I have the same problem as just filter on page 1, but I don't understand the solution they give with filter-change
