### ISSUE TITLE
在el-table-column 中使用 :formatter='dateFormater' 的问题

### ISSUE THREAD

**Issue by o3661606** [njleonzhang/vue-data-tables#57]
我在el-table-column 中用了

>  :formatter='dateFormater'

 去转换时间的显示格式，
我发现search box会用`el-table-column`内`prop`的值(e.g. 2017-07-14T09:17:18.824Z) 作为搜索条件， 而不是用转换後的值(e.g. 2017-07-14 05:17 PM ) 
请问这个问题可以怎样解决？

谢谢？

**Comment by njleonzhang** [comment]
用search box 的filterFunction 自定义一个比较函数应该就能解决了
