### ISSUE TITLE
Sorting error

### ISSUE THREAD

**Issue by Lazac92** [njleonzhang/vue-data-tables#6]
If i want to short my table, i get this warning to the console:

[Vue warn]: You may have an infinite update loop in a component render function. 
(found in component <DataTables>)

I checked your demo, and the 1st table do the same, the others don't.

**Comment by njleonzhang** [comment]
@Lazac92 Thanks, fix it. And release new version, please update the lib via npm and try again.

**Comment by Lazac92** [comment]
Thank you!
