### ISSUE TITLE
unable to figure out how to do a v-if on each table row

### ISSUE THREAD

**Issue by ettaegbe** [njleonzhang/vue-data-tables#60]
Sorry putting this in issues. Didn't find where to ask for this help.
I'm using lib on my project a couldn't figure how to do something.
Please how do a v-if so it will show a row on depending a condition. I have look a your get start but couldn't find a solution. please can you just give a link jsfiddle.
Thanks. close this only if you have a solution to it.

**Comment by njleonzhang** [comment]
you can remove the object from the `data` list and render the table
