### ISSUE TITLE
Custom sort

### ISSUE THREAD

**Issue by TKafassis** [njleonzhang/vue-data-tables#62]
I tried to use custom sort as it's described in element ui documentation in a data-table, but the event is not firing when sort apply in the table. More specifically i added sortable="custom" to an el-table-colunm and @sort-change to the table, but the event in not triggered. Please let me know if there is another way to do custom sorting. 
Also even though it's not relevant with the sorting, there is a way to add placeholder to search box filter?

**Comment by njleonzhang** [comment]
`sort-change` proxied in 2.0.2
about the `placeholder`, I have updated the [document](https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=customize-the-input)
