### ISSUE TITLE
Get data with ajax.

### ISSUE THREAD

**Issue by BangShut** [njleonzhang/vue-data-tables#63]
How get data from server with ajax in pagination ?

**Comment by sobolevn** [comment]
I confirm that this is an issue. Since it is not a trivial thing to do, keeping in mind all the possible filters, orderings and searching.

@BangShut did you come up with any solution?

**Comment by njleonzhang** [comment]
currently, this component is for font-end data source. the pagination is calculated by `data` and `page-size`. I will consider to make it work with server data source.

**Comment by njleonzhang** [comment]
released in 2.1.0
