### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by sobolevn** [njleonzhang/vue-data-tables#64]
What browser does this library support?

I need to support `ie10+`. Is it possible?

P.S. Maybe you should clarify that in a readme?

**Comment by njleonzhang** [comment]
should be same as Vue and element-ui. will test ASAP, may be a build issue.

**Comment by njleonzhang** [comment]
can you provide the error you encounter in low version IE? I don't have IE environment at hand

**Comment by sobolevn** [comment]
Thanks! I don't have any bugs yet, because I have not started yet. 
I am just planning and choosing dependencies.

**Comment by njleonzhang** [comment]
OK

**Comment by sobolevn** [comment]
I still insist on adding this information to the readme. Since it is valuable when making decisions.

**Comment by njleonzhang** [comment]
@sobolevn will add later, thanks for suggestion. In addition, if possible, would you please help to review my readme? You know, I am not native english speaker.

**Comment by sobolevn** [comment]
Sure! But I am Russian, so not a native speaker either.

**Comment by njleonzhang** [comment]
😂
