### ISSUE TITLE
@sort-change didn't work

### ISSUE THREAD

**Issue by reclay** [njleonzhang/vue-data-tables#65]
# Online reproduce
[https://jsfiddle.net/krtphh36/](https://jsfiddle.net/krtphh36/)

## Context
add sort-change to data-tables but didn't work

**Comment by njleonzhang** [comment]
sry for forgetting to update the lib link in sample.
 please use master version. 

<script src="https://rawgit.com/njleonzhang/vue-data-tables/master/dist/data-tables.js"></script>

**Comment by reclay** [comment]
Thanks
