### ISSUE TITLE
使用v-if做表格切换时，表格显示异常

### ISSUE THREAD

**Issue by lxyzxq2008** [njleonzhang/vue-data-tables#66]
表格在动态切换的时候，表格不能正常显示，只能显示出一列，而且还占据了整个表格的宽度，怎么解决一下这个问题呢？

**Comment by njleonzhang** [comment]
请具体给个在线的sample吧

**Comment by lxyzxq2008** [comment]
el-table  是否有这个问题我不清楚，我直接使用的这个组件，大概的效果是这样的:
开始显示表格(正常)：
table1
列1  列2  列3  列4
根据条件切换显示(异常)：
table2
列1
table2只显示了一列，而且占据了列1到列4的整个宽度；
在切换到显示表格table1，也出现显示异常，同样只显示了一列，而且占据了列1到列4的整个宽度；

**Comment by njleonzhang** [comment]
你的意思我大概明白，最好你能修改下这个[jsfiddle](http://jsfiddle.net/zpczjl/9tp3z4bn/) ，能重现问题是最好的，一方面让我看到你的代码，能够最终确认到底是谁的问题。

**Comment by njleonzhang** [comment]
我试着用了一下v-if 未发现问题。

http://jsfiddle.net/zpczjl/yLocahsk/1/

**Comment by lxyzxq2008** [comment]
我把现象再现了一下：https://jsfiddle.net/yLocahsk/24/    点击change按钮会切换，现象就出现了

**Comment by njleonzhang** [comment]
哦 你是在`el-table-column`上用v-if进行切换啊。我试了一下`el-table`本身就有问题哦，你可能需要去`el-table`那边提问题了。或者直接去看下源码。可以临时做2个表来处理。
https://github.com/ElemeFE/element/issues/4636  你可以参考这个链接看看能不能解决。

**Comment by joshchiucn** [comment]
![default](https://user-images.githubusercontent.com/20282988/30676415-a9f43b40-9eb8-11e7-9e33-a3af1b4775ad.png)
table-layout.js 文件里，计算行宽的时候：`bodyMinWidth += column.width || column.minWidth || 80;`  当你给列自定宽度的时候，这里column.width是String,所以+=然后，‘50’+‘50’+'50'=‘505050’（px）

**Comment by njleonzhang** [comment]
@joshchiucn 感谢解释
