### ISSUE TITLE
Table data with anchor or button element

### ISSUE THREAD

**Issue by Reechee88** [njleonzhang/vue-data-tables#69]
I would like to make some data as anchor element and I try to pass the data like this:
```

data = [{
  "content": "<a href='#'>Water flood</a>",
  "flow_no": "FW201601010001",
}];

```
Of course, it is not binded as v-html, so it doesn't understand what I want.

Is there a way to accomplish this task?

Thanks!

**Comment by njleonzhang** [comment]
maybe you can try leverage [custom-column-template](http://element.eleme.io/#/en-US/component/table#custom-column-template)

**Comment by Reechee88** [comment]
Yeah, I found that also. But how do I use with your component?

**Comment by njleonzhang** [comment]
look at the [sample](https://njleonzhang.github.io/vue-data-tables/#/renderTable?id=basic-table)
just use `el-table-column` inside this component. this component is a wrapper of `el-table`. so you can use `el-table-column` just as `el-table`

**Comment by Reechee88** [comment]
Working like a charm! I am sehr happy, thank you! :)
