### ISSUE TITLE
Remote filtering and searching

### ISSUE THREAD

**Issue by jiriko** [njleonzhang/vue-data-tables#7]
Hi, 

How to do service side processing for search and filtering?

**Comment by njleonzhang** [comment]
This component need the data source. Look at the demo. Just init your `data` in created by ajax request. [demo line171](https://github.com/njleonzhang/vue-data-tables/blob/master/example/docs/en.vue#L171)

```
  created() {
    // You can make a ajax request to init tableData.
    for (var i = 0; i < 100; i++) {
      this.tableData = this.tableData.concat(en)
    }
  }
```

**Comment by njleonzhang** [comment]
This lib focus on client filter and search. for server side process, you can just use element-ui's `el-table`. every time you make search or filtering, just send a request to sever and update the data, then make the `el-table` re-render. You need handle the pagination yourself, you refer to this lib's source code.

For this lib, if I provide a method for disable client search and filter, and just proxy the event, then it can meet your requirement.

**Comment by jiriko** [comment]
I was thinking of something similar to JQuery DataTables server side processing.
I thought I missed something.

Thanks man. 
Great job btw!
