### ISSUE TITLE
Total don't work

### ISSUE THREAD

**Issue by thearabbit** [njleonzhang/vue-data-tables#73]
I base on `Meteor + Vue`.
![image](https://user-images.githubusercontent.com/4495160/29063493-44721cc2-7c50-11e7-9062-4d106a2a223c.png)

**Comment by nosnaj** [comment]
@thearabbit Can you please provide a snippet of your code, or a jsfiddle example of your implementation?

**Comment by njleonzhang** [comment]
close for no reproduction, reopen if you can provide a online reproduction

**Comment by thearabbit** [comment]
Sorry I am late, it work fine on `jsFiddle`.
But don't work in my project `Meteor + Vue`

**Comment by njleonzhang** [comment]
@thearabbit Maybe you can try to debug by yourself, I do not have Meteor environment at hand.
