### ISSUE TITLE
possible to transform data in columns for display?

### ISSUE THREAD

**Issue by ssuess** [njleonzhang/vue-data-tables#74]
Is it possible to transform the data in my dataset before table display? For example, my dataset returns a unix timestamp and I would like to display it as an english date. (I already have moment installed btw.)

**Comment by njleonzhang** [comment]
yeah, you can customize. look at: https://github.com/njleonzhang/vue-data-tables/issues/69

**Comment by ssuess** [comment]
Thanks, I took a look there and am not sure how to proceed. Is there any example that would show filtering on the data output for that column? ie something like a filter I have (formatUnix) that returns a value like `return moment(this.posts.date, 'X').format('YYYY-MM-DD')`

**Comment by njleonzhang** [comment]
check this sample: 
https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=customize-filter-logic
