### ISSUE TITLE
Document is not working

### ISSUE THREAD

**Issue by AtticusLv** [njleonzhang/vue-data-tables#75]
# Online reproduce
`<data-tables
    ref="multipleTable"
    :data="productTypeTableList"
    height="350"
    border
    style="width: 100%"
    :has-action-col="false">
        <el-table-column
          prop="productTypeTableList.productType"
          label="ProductType"
          width="120">
        </el-table-column>`

## Context
Searching is not working when I use context of objects, eg. use 'productTypeTableList.productType' in Props of el-table-column. Pls refer to above codes. 
BTW,
I remember details and templates of using this extension were provided before, but I couldn't find them now at https://njleonzhang.github.io/vue-data-tables/
Pls provide that. Many thanks

**Comment by njleonzhang** [comment]
不好意思我英文不太好，不太看得明白你的意思。 从你的代码来看，我只是觉得`productTypeTableList.productType`有点奇怪， `productTypeTableList`是一个列表，你给他设置了一个属性么？你需要什么文档？

关于搜索的文档都在这：
```
https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter
```

**Comment by AtticusLv** [comment]
抱歉哈，以为你是外国人，就是要那个搜索的文档！感谢感谢
忽略上面那个bug，是我自己犯错
