### ISSUE TITLE
Search action does not fire any events

### ISSUE THREAD

**Issue by sobolevn** [njleonzhang/vue-data-tables#77]
It is stated in the docs:

> filtered-data
> trigger when any filter change(search box, checkbox, sort or customFilters), and pass filted data out.

But actually fires only here: https://github.com/njleonzhang/vue-data-tables/blob/f98b32d4c0a97ca6c072cfd6b524c4fb941058de/src/components/DataTables.vue#L45

Any ideas on how to fix that?

**Comment by njleonzhang** [comment]
https://github.com/njleonzhang/vue-data-tables/blob/f98b32d4c0a97ca6c072cfd6b524c4fb941058de/src/components/DataTables.vue#L342

it should emit when any filter change

**Comment by sobolevn** [comment]
That would be very helpful. 

What I am trying to achieve:
1. I have a lot of data. Like 100.000s of data
2. I want to display it with `vue-data-tables`
3. It does not fit into memory obviously 
4. So I want to paginate it on server
5. I need criteria to paginate the data, like: search, checkboxes, ordering, column filters
6. I can not get it right now

It is all related to the #63

**Comment by njleonzhang** [comment]
Yeah, this component can not work with server data source. I think just some change on the pagination caculate can make it work.

**Comment by thearabbit** [comment]
@sobolevn, I need this option too 👍

**Comment by njleonzhang** [comment]
so many enhancements.....no PRs......crazy~~~

**Comment by nWidart** [comment]
I'd very much love this as well. 🙏  I don't have the required JS skills to PR this though. 😞

**Comment by njleonzhang** [comment]
@nWidart I  am working on server version. You can refer to https://github.com/njleonzhang/vue-data-tables/tree/server_data_support

**Comment by njleonzhang** [comment]
for server version, released in 2.1.0

**Comment by njleonzhang** [comment]
default action bar is removed in 3.4.0, please defined your own customize tool bar
