### ISSUE TITLE
关于搜索

### ISSUE THREAD

**Issue by wuhaohuang** [njleonzhang/vue-data-tables#78]
## 问题1：每条数据中有个state来表示该条数据的状态，返回状态是个0||1||2||3||....
会对返回的状态进行一个模板转换，例如0对应=>已使用,123..相对的转换到表格中显示，在搜索中进行搜索的时候按照文档中自定义搜索的方法filterFunction去模仿写，并不能搜索到，不知道是不是我没有写对

## 问题2：当数据中含有某些字段未在图表中进行使用渲染的时候
每当进行搜索的时候会报错：prop xxxxxx not exist in the row, please confirm wether the prop is right, this may cause unpredictable filter result
我想请求回来的数据并不会都会用到吧

**Comment by njleonzhang** [comment]
@wuhaohuang 请提供在线的重现例子，以便我查看。
参考这个jsfiddle来写： http://jsfiddle.net/zpczjl/9tp3z4bn/

```
prop xxxxxx not exist in the row, please confirm wether the prop is right, this may cause unpredictable filter result
```
这个警告是说这个prop `xxxxx`，并不存在于你的数据里，比如你的数据格式是：
```
[{
  a: 1,
  b: 2
}]
```
但是你的某列的prop写了`c`，这就会导致上述的warning. 请检查你的prop写的是否有笔误。
如果你发现行为不对，请提供重现样例。

**Comment by wuhaohuang** [comment]
请观察jsfiddle,地址：https://jsfiddle.net/hughwu/6cbbta6q/
1.搜索栏中搜索腾讯或者阿里搜索不到
2.搜索栏中搜索任何都会报prop xxxxxx not exist in the row, please confirm wether the prop is right, this may cause unpredictable filter result
且没有您说的那种行为，请看看怎么回事~麻烦了

**Comment by njleonzhang** [comment]
不好意思，最近项目很忙没有及时回复。这个确实是一个bug，你的数据里有0，被当成了空数据。

**Comment by njleonzhang** [comment]
另外你下面的函数写错了。......
```
    getSearchDef () {
      let self = this
      return {
        data: self.$data.tableData,
        searchDef: {
          filterFunction: (el, filter) => {
            return Object.keys(el).some(prop => {
          	console.log(el, filter)
						if (prop === 'couponsType') {
                return this.getCouponsType(el.couponsType).indexOf(filter.vals[0]) > -1
              } else {
                return el[prop].toLowerCase().indexOf(filter.vals[0].toLowerCase()) > -1
              }
            })
          }
        }
      }
    }
```

**Comment by wuhaohuang** [comment]
@njleonzhang 你好，请问正确的应该怎么写？

**Comment by njleonzhang** [comment]
@wuhaohuang 参见例子啊。
https://njleonzhang.github.io/vue-data-tables/#/searchBoxFilter?id=customize-filter-logic

getSearchDef() 你应该返回一个和例子里一样的对象`filterFunction`是他的一个属性。你写的明显不对，你仔细看一下就知道了

```
  data() {
    return {
      data,
      titles,
      searchDef: {
        filterFunction: (el, filter) => {
          return Object.keys(el).some(prop => {
            if (prop === 'date') {
              return this.getDate(el.date).indexOf(filter.vals[0]) > -1
            } else {
              return el[prop].toLowerCase().indexOf(filter.vals[0].toLowerCase()) > -1
            }
          })
        }
      }
    }
  }
```
