### ISSUE TITLE
console.log in innerPaginationDef in DataTables.vue

### ISSUE THREAD

**Issue by tnerbovik** [njleonzhang/vue-data-tables#8]

**Comment by njleonzhang** [comment]
Tnx! have removed it.  eb0106ab14db08e8058b5586197b5665ac4cc8bc

**Comment by tnerbovik** [comment]
(There is also the same in the dist-folder)

It is a great package by the way. Thanks!

**Comment by njleonzhang** [comment]
@tnerbovik I have not released this fix. release now.
