### ISSUE TITLE
Refresh data vue-data-tables

### ISSUE THREAD

**Issue by daviddsp** [njleonzhang/vue-data-tables#85]
Hi community!

I have a problem, 
I got edit method in my view component, need update refresh data on my vue-data-table

Some ideas?, 

Thanks..
![captura de pantalla de 2017-09-03 23-16-06](https://user-images.githubusercontent.com/2723396/30009357-1995a68c-90fe-11e7-8876-1195ccf3360e.png)

**Comment by njleonzhang** [comment]
https://njleonzhang.github.io/vue-data-tables/#/quickstart?id=hello-word
check this demo, just revise the row, then the data should be update automatically by vue.
