### ISSUE TITLE
Refresh table automatically

### ISSUE THREAD

**Issue by daviddsp** [njleonzhang/vue-data-tables#87]
Hi community!

I need to refresh a table automatically every 3 minutes.
Can you help me please?
![captura de pantalla de 2017-09-07 00-23-11](https://user-images.githubusercontent.com/2723396/30144636-cadadba4-9362-11e7-808d-cf14ce9b1115.png)

**Comment by njleonzhang** [comment]
set a timer in your vue `create()` or some other place you want. then update the table data in the timer.

**Comment by daviddsp** [comment]
Thanks for you answer, You recommend me refresh my view component?

**Comment by njleonzhang** [comment]
assign new value from ajax to table `data`, then the table will be refreshed automatically by Vue.

**Comment by daviddsp** [comment]
@njleonzhang thanks
