### ISSUE TITLE
data-tables-server > row-class-name : el-table : element-ui

### ISSUE THREAD

**Issue by leiha** [njleonzhang/vue-data-tables#93]
Hi, and ty for the contribution ;)

## Context
i tried to use the native row-class-name with data-tables-server and apparently it seems doesn't work
Normal ? ( when i use el-table the same thing works like a charm )

**Comment by njleonzhang** [comment]
would you please provide a sample to reproduce this issue based on the following jsfiddle demo

https://jsfiddle.net/zpczjl/xboja87c/

**Comment by leiha** [comment]
https://jsfiddle.net/xboja87c/1/

**Comment by leiha** [comment]
never mind it's my fault i understood my mistake : https://jsfiddle.net/xboja87c/5/
I must learn to read the documentation ;)

**Comment by njleonzhang** [comment]
I set el-table `stripe` to true in this lib, you need set `stripe` as false in your case.

https://jsfiddle.net/zpczjl/xxbtwszt/

**Comment by leiha** [comment]
ah ok simply
Ty and again good job ;)

**Comment by njleonzhang** [comment]
BTW, you can write `row-class-name` as `rowClassName`, which may make you feel better when write js

**Comment by juzai123** [comment]
请问这里的属性可以直接调用methods中的方法吗，因为这个我需要在这个function中调用data中的数据，比如这里在      	
"row-class-name" : function ( row, index ) {
    	  console.log( row )
          console.log(this.tableProps.stripe)
    	  return 'fail'         
}

console.log(this.tableProps.stripe)  会有undefinded的问题
或者有没有其他可变通的方法？谢谢指教
