### ISSUE TITLE
Upgrade Element 2.0 - [Vue Warn] Injection "elFormItem" not found

### ISSUE THREAD

**Issue by globsecure** [njleonzhang/vue-data-tables#94]
Hello,

The warning happens only when you upgrade to a new version of Element-UI. I believe it is a problem of just updating and not of datatable.

**Comment by njleonzhang** [comment]
would you please provide a reproduce demo refer to http://jsfiddle.net/zpczjl/9tp3z4bn/

**Comment by globsecure** [comment]
Sorry @njleonzhang, 

Code: http://jsfiddle.net/9tp3z4bn/129/

![screen shot 2017-10-09 at 22 54 54](https://user-images.githubusercontent.com/1958192/31365955-ef9924e0-ad44-11e7-8e4c-1289f0216ff9.png)

**Comment by njleonzhang** [comment]
@globsecure never mind. Tnx for your contribution anyway. 👍

**Comment by juzai123** [comment]
element ui 2.0 is in beta now, it that possible this project can support 2.0 now? Thx

**Comment by njleonzhang** [comment]
@juzai123 will support ASAP. You can have a try and check if you would encounter any issue.

**Comment by jiangxiaoxin** [comment]
@globsecure you should update vue and vue-template-compiler as well if you update element-ui to version 2. vue and vue-template-compiler should be version 2.5.3

**Comment by Emo1995** [comment]
@jiangxiaoxin Thxs very much.

**Comment by xiwu12138** [comment]
@jiangxiaoxin   the version of vue and vue-template-compiler is 2.5.3  ,the element ui version is 2.2.1, also happen this problem:[Vue warn]: Injection "elFormItem" not found ,can  you  give me some suggestion or thinking?

**Comment by ducaiwei** [comment]
@jiangxiaoxin the version of vue and vue-template-compiler is 2.5.16 ,the element ui version is 2.4.2, also happen this problem:[Vue warn]: Injection "elFormItem" not found ,can you give me some suggestion or thinking?

**Comment by llojkue** [comment]
Did anyone found a solution???
