### ISSUE TITLE
Render HTML in cells

### ISSUE THREAD

**Issue by wxkin** [njleonzhang/vue-data-tables#96]
Hi there, this is not really an issue is more like a feature request.

Is it possible to render HTML in data table cell? It would be really handy if could be able to have HTML syntax in cells. We could style the elements or even have hyperlinks.
e.g:
```
data: [
 { 
  'fileName': '<span class="glyphicon glyphicon-text"></span> <a href="/download/file.txt>file</a>',
  'size': '100 kB'
 }
]
```

**Comment by njleonzhang** [comment]
You should be able to do this with `v-html` and [custom-column-template](http://element.eleme.io/#/en-US/component/table#custom-column-template)

**Comment by njleonzhang** [comment]
no response and should be able to solved by above suggestion. close it.
