### ISSUE TITLE
清除搜索后 fixed列 内容变成透明

### ISSUE THREAD

**Issue by exuan** [njleonzhang/vue-data-tables#97]
如图，
![edit-fiddle-jsfiddle-google-chrome-2017_10_19-15_21_00](https://user-images.githubusercontent.com/1683921/31759081-c42067f6-b4e2-11e7-997a-6ded200033fe.gif)

**Comment by njleonzhang** [comment]
这个问题是element-ui `append slot`和column fixed之间的一个冲突，使用`el-table`重现这个问题：
http://jsfiddle.net/zpczjl/4ctx4kr5/ 

我会去element-ui那边提个issus

如果你需要用的话，你可以删除下面这2句代码，自己编译一个版本就可以使用了。

https://github.com/njleonzhang/vue-data-tables/blob/d3ed7151864a349014b1c0509f376f204399f81d/src/template/index.pug#L36-L37

**Comment by exuan** [comment]
感谢了，老铁，暂时把搜索关闭了，

**Comment by njleonzhang** [comment]
@exuan 不知搜索会出问题，只要你用fixed column，然后改变表里内容的个数，都会出这个问题。所以如果你要用fixed column我建议你拉源码改一下再用。如果fixed column用的人多，我会暂时把库的代码改掉。

**Comment by njleonzhang** [comment]
element-ui bug link： https://github.com/ElemeFE/element/issues/7594

**Comment by exuan** [comment]
get

**Comment by njleonzhang** [comment]
it's fixed by element-ui 2.0, which is supported by vue-data-tables 3.0, please update to fix this issue.
